// Interactive stratified hot water tank charged by a heat pump (anywidget module for MyST).
// Same model as dhw_tank.py, which is the documented reference version.

export const DEFAULTS = {
  V_tank: 200, H_tank: 1.2, n_layers: 30, UA: 1.2, T_room: 20, k_eff: 1.5, inlet_pos: 50,
  P_hp: 3, T_hp_max: 65, hex_approach: 5, flow_ch: 2, T_source: 7, eta_carnot: 0.5,
  T_set: 55, hyst: 5, sensor_pos: 60, T_cold: 10, use_scale: 100, days: 3,
};

// Tapping profiles: [start time h, name, volume at the tap L, flow at the tap L/min, use temperature C].
// PROFILE_INFO holds the group, the literature reference and how each profile was built.
// --- profiles (generated by build_profiles.py) ---
export const PROFILES = {
  "EN 16147 M": [[7.0, "small", 6.1, 3, 25], [7.083333333333333, "shower", 40.4, 6, 40], [7.5, "small", 6.1, 3, 25], [8.016666666666667, "small", 6.1, 3, 25], [8.25, "small", 6.1, 3, 25], [8.5, "small", 6.1, 3, 25], [8.75, "small", 6.1, 3, 25], [9.0, "small", 6.1, 3, 25], [9.5, "small", 6.1, 3, 25], [10.5, "floor cleaning", 3.0, 3, 40], [11.5, "small", 6.1, 3, 25], [11.75, "small", 6.1, 3, 25], [12.75, "dishwashing", 6.1, 4, 55], [14.5, "small", 6.1, 3, 25], [15.5, "small", 6.1, 3, 25], [16.5, "small", 6.1, 3, 25], [18.0, "small", 6.1, 3, 25], [18.25, "cleaning", 3.0, 3, 40], [18.5, "cleaning", 3.0, 3, 40], [19.0, "small", 6.1, 3, 25], [20.5, "dishwashing", 14.1, 4, 55], [21.25, "small", 6.1, 3, 25], [21.5, "shower", 40.4, 6, 40]],
  "EN 16147 L": [[7.0, "small", 6.1, 3, 25], [7.083333333333333, "shower", 40.4, 6, 40], [7.5, "small", 6.1, 3, 25], [7.75, "small", 6.1, 3, 25], [8.083333333333334, "bath", 104.1, 10, 40], [8.416666666666666, "small", 6.1, 3, 25], [8.5, "small", 6.1, 3, 25], [8.75, "small", 6.1, 3, 25], [9.0, "small", 6.1, 3, 25], [9.5, "small", 6.1, 3, 25], [10.5, "floor cleaning", 3.0, 3, 40], [11.5, "small", 6.1, 3, 25], [11.75, "small", 6.1, 3, 25], [12.75, "dishwashing", 6.1, 4, 55], [14.5, "small", 6.1, 3, 25], [15.5, "small", 6.1, 3, 25], [16.5, "small", 6.1, 3, 25], [18.0, "small", 6.1, 3, 25], [18.25, "cleaning", 3.0, 3, 40], [18.5, "cleaning", 3.0, 3, 40], [19.0, "small", 6.1, 3, 25], [20.5, "dishwashing", 14.1, 4, 55], [20.766666666666666, "bath", 104.1, 10, 40], [21.5, "small", 6.1, 3, 25]],
  "EN 16147 XL": [[7.0, "small", 6.1, 3, 25], [7.25, "shower", 52.5, 6, 40], [7.433333333333334, "small", 6.1, 3, 25], [7.75, "bath", 127.6, 10, 40], [8.016666666666667, "small", 6.1, 3, 25], [8.25, "small", 6.1, 3, 25], [8.5, "small", 6.1, 3, 25], [8.75, "small", 6.1, 3, 25], [9.0, "small", 6.1, 3, 25], [9.5, "small", 6.1, 3, 25], [10.0, "small", 6.1, 3, 25], [10.5, "floor cleaning", 3.0, 3, 40], [11.0, "small", 6.1, 3, 25], [11.5, "small", 6.1, 3, 25], [11.75, "small", 6.1, 3, 25], [12.75, "dishwashing", 14.1, 4, 55], [14.5, "small", 6.1, 3, 25], [15.0, "small", 6.1, 3, 25], [15.5, "small", 6.1, 3, 25], [16.0, "small", 6.1, 3, 25], [16.5, "small", 6.1, 3, 25], [17.0, "small", 6.1, 3, 25], [18.0, "small", 6.1, 3, 25], [18.25, "cleaning", 3.0, 3, 40], [18.5, "cleaning", 3.0, 3, 40], [19.0, "small", 6.1, 3, 25], [20.5, "dishwashing", 14.1, 4, 55], [20.766666666666666, "bath", 127.6, 10, 40], [21.25, "small", 6.1, 3, 25], [21.5, "bath", 127.6, 10, 40]],
  "IEA SHC Task 26, weekday": [[5.321428571428571, "short", 1, 1, 45], [5.45, "medium", 6, 6, 45], [5.964285714285714, "short", 1, 1, 45], [6.607142857142858, "short", 1, 1, 45], [6.95, "medium", 6, 6, 45], [7.0, "shower", 40, 8, 45], [7.25, "short", 1, 1, 45], [7.892857142857142, "short", 1, 1, 45], [8.45, "medium", 6, 6, 45], [8.535714285714285, "short", 1, 1, 45], [9.178571428571429, "short", 1, 1, 45], [9.821428571428571, "short", 1, 1, 45], [9.95, "medium", 6, 6, 45], [10.464285714285715, "short", 1, 1, 45], [11.107142857142858, "short", 1, 1, 45], [11.45, "medium", 6, 6, 45], [11.75, "short", 1, 1, 45], [12.392857142857142, "short", 1, 1, 45], [12.95, "medium", 6, 6, 45], [13.035714285714286, "short", 1, 1, 45], [13.678571428571429, "short", 1, 1, 45], [14.321428571428571, "short", 1, 1, 45], [14.45, "medium", 6, 6, 45], [14.964285714285714, "short", 1, 1, 45], [15.607142857142858, "short", 1, 1, 45], [15.950000000000001, "medium", 6, 6, 45], [16.25, "short", 1, 1, 45], [16.892857142857142, "short", 1, 1, 45], [17.450000000000003, "medium", 6, 6, 45], [17.535714285714285, "short", 1, 1, 45], [18.17857142857143, "short", 1, 1, 45], [18.82142857142857, "short", 1, 1, 45], [18.950000000000003, "medium", 6, 6, 45], [19.464285714285715, "short", 1, 1, 45], [19.5, "shower", 40, 8, 45], [20.107142857142858, "short", 1, 1, 45], [20.450000000000003, "medium", 6, 6, 45], [20.75, "short", 1, 1, 45], [21.392857142857142, "short", 1, 1, 45], [21.95, "medium", 6, 6, 45], [22.035714285714285, "short", 1, 1, 45], [22.678571428571427, "short", 1, 1, 45]],
  "IEA SHC Task 26, bath day": [[5.321428571428571, "short", 1, 1, 45], [5.45, "medium", 6, 6, 45], [5.964285714285714, "short", 1, 1, 45], [6.607142857142858, "short", 1, 1, 45], [6.95, "medium", 6, 6, 45], [7.0, "shower", 40, 8, 45], [7.25, "short", 1, 1, 45], [7.892857142857142, "short", 1, 1, 45], [8.45, "medium", 6, 6, 45], [8.535714285714285, "short", 1, 1, 45], [9.178571428571429, "short", 1, 1, 45], [9.821428571428571, "short", 1, 1, 45], [9.95, "medium", 6, 6, 45], [10.464285714285715, "short", 1, 1, 45], [11.107142857142858, "short", 1, 1, 45], [11.45, "medium", 6, 6, 45], [11.75, "short", 1, 1, 45], [12.392857142857142, "short", 1, 1, 45], [12.95, "medium", 6, 6, 45], [13.035714285714286, "short", 1, 1, 45], [13.678571428571429, "short", 1, 1, 45], [14.321428571428571, "short", 1, 1, 45], [14.45, "medium", 6, 6, 45], [14.964285714285714, "short", 1, 1, 45], [15.607142857142858, "short", 1, 1, 45], [15.950000000000001, "medium", 6, 6, 45], [16.25, "short", 1, 1, 45], [16.892857142857142, "short", 1, 1, 45], [17.450000000000003, "medium", 6, 6, 45], [17.535714285714285, "short", 1, 1, 45], [18.17857142857143, "short", 1, 1, 45], [18.82142857142857, "short", 1, 1, 45], [18.950000000000003, "medium", 6, 6, 45], [19.464285714285715, "short", 1, 1, 45], [19.5, "shower", 40, 8, 45], [20.107142857142858, "short", 1, 1, 45], [20.25, "bath", 140, 14, 45], [20.450000000000003, "medium", 6, 6, 45], [20.75, "short", 1, 1, 45], [21.392857142857142, "short", 1, 1, 45], [21.95, "medium", 6, 6, 45], [22.035714285714285, "short", 1, 1, 45], [22.678571428571427, "short", 1, 1, 45]],
  "Danish house, 4 persons": [[6.6, "kitchen tap", 1.5, 6, 25], [6.65, "washbasin", 1, 5, 23], [6.75, "shower", 52, 7, 38], [6.9, "kitchen tap", 1.5, 6, 25], [7.0, "washbasin", 1, 5, 23], [7.1, "kitchen tap", 1.5, 6, 25], [7.2, "washbasin", 1, 5, 23], [7.3, "kitchen tap", 1.5, 6, 25], [7.4, "washbasin", 1, 5, 23], [7.5, "kitchen tap", 1.5, 6, 25], [8.0, "kitchen tap", 1.5, 6, 25], [12.0, "kitchen tap", 1.5, 6, 25], [12.2, "kitchen tap", 1.5, 6, 25], [15.5, "kitchen tap", 1.5, 6, 25], [16.0, "kitchen tap", 1.5, 6, 25], [16.5, "kitchen tap", 1.5, 6, 25], [17.0, "kitchen tap", 1.5, 6, 25], [17.3, "kitchen tap", 1.5, 6, 25], [17.6, "kitchen tap", 1.5, 6, 25], [17.9, "kitchen tap", 1.5, 6, 25], [18.2, "kitchen tap", 1.5, 6, 25], [18.5, "kitchen tap", 1.5, 6, 25], [18.8, "kitchen tap", 1.5, 6, 25], [19.0, "kitchen tap", 1.5, 6, 25], [19.2, "kitchen tap", 1.5, 6, 25], [19.5, "shower", 52, 7, 38], [19.7, "kitchen tap", 1.5, 6, 25], [20.0, "kitchen tap", 1.5, 6, 25], [20.3, "kitchen tap", 1.5, 6, 25], [20.6, "kitchen tap", 1.5, 6, 25], [21.0, "kitchen tap", 1.5, 6, 25], [21.5, "kitchen tap", 1.5, 6, 25], [21.8, "washbasin", 1, 5, 23], [22.0, "washbasin", 1, 5, 23], [22.2, "washbasin", 1, 5, 23], [22.4, "washbasin", 1, 5, 23]],
  "Danish house, 2 persons": [[7.0, "shower", 42, 7, 38], [7.1, "washbasin", 1, 5, 23], [7.2, "kitchen tap", 1.5, 6, 35], [7.4, "washbasin", 1, 5, 23], [7.5, "kitchen tap", 1.5, 6, 35], [12.0, "kitchen tap", 1.5, 6, 35], [17.5, "kitchen tap", 1.5, 6, 35], [18.0, "kitchen tap", 1.5, 6, 35], [18.3, "kitchen tap", 1.5, 6, 35], [18.6, "kitchen tap", 1.5, 6, 35], [19.0, "kitchen tap", 1.5, 6, 35], [19.3, "kitchen tap", 1.5, 6, 35], [20.0, "kitchen tap", 1.5, 6, 35], [21.0, "kitchen tap", 1.5, 6, 35], [22.0, "washbasin", 1, 5, 23], [22.2, "washbasin", 1, 5, 23]],
  "Family of 4, morning and evening": [[6.5, "shower", 42, 7, 40], [6.75, "shower", 42, 7, 40], [7.0, "washbasin", 3, 5, 35], [7.1, "washbasin", 3, 5, 35], [7.25, "kitchen tap", 2, 6, 45], [7.5, "washbasin", 3, 5, 35], [12.0, "kitchen tap", 3, 6, 45], [17.5, "kitchen tap", 4, 6, 45], [18.0, "washbasin", 3, 5, 35], [19.0, "washing up", 10, 6, 45], [20.0, "shower", 42, 7, 40], [21.5, "washbasin", 3, 5, 35], [21.6, "washbasin", 3, 5, 35], [22.0, "kitchen tap", 2, 6, 45]],
  "Family of 4, all showers in the evening": [[7.0, "washbasin", 3, 5, 35], [7.1, "washbasin", 3, 5, 35], [7.25, "kitchen tap", 2, 6, 45], [7.5, "washbasin", 3, 5, 35], [12.0, "kitchen tap", 3, 6, 45], [17.5, "kitchen tap", 4, 6, 45], [18.0, "washbasin", 3, 5, 35], [19.0, "washing up", 10, 6, 45], [19.5, "shower", 42, 7, 40], [19.75, "shower", 42, 7, 40], [20.0, "shower", 42, 7, 40], [21.5, "washbasin", 3, 5, 35], [21.6, "washbasin", 3, 5, 35], [22.0, "kitchen tap", 2, 6, 45]],
  "Couple, morning showers": [[6.5, "shower", 42, 7, 40], [6.8, "shower", 42, 7, 40], [7.1, "washbasin", 3, 5, 35], [7.25, "kitchen tap", 2, 6, 45], [17.5, "kitchen tap", 3, 6, 45], [19.0, "washing up", 8, 6, 45], [22.0, "washbasin", 3, 5, 35], [22.1, "washbasin", 3, 5, 35]],
};
export const PROFILE_INFO = {
  "EN 16147 M": {"group": "Standard test cycles", "cite": "Reg. (EU) 814/2013 / EN 16147", "ref": "Commission Regulation (EU) No 814/2013, Annex III, Table 1 (load profiles used for ecodesign and energy labelling; the same profiles are used in EN 16147 for heat pump water heaters).", "url": "https://eur-lex.europa.eu/eli/reg/2013/814/oj", "note": "Times, energies and flows as in the regulation. Energies are converted to litres at the use temperature: Tp where the table gives one (bath and floor cleaning 40 °C, dishwashing 55 °C), otherwise Tm (small tappings 25 °C, shower and cleaning 40 °C). Cold water 10 °C. Typical for 1–2 persons."},
  "EN 16147 L": {"group": "Standard test cycles", "cite": "Reg. (EU) 814/2013 / EN 16147", "ref": "Commission Regulation (EU) No 814/2013, Annex III, Table 1 (load profiles used for ecodesign and energy labelling; the same profiles are used in EN 16147 for heat pump water heaters).", "url": "https://eur-lex.europa.eu/eli/reg/2013/814/oj", "note": "Times, energies and flows as in the regulation. Energies are converted to litres at the use temperature: Tp where the table gives one (bath and floor cleaning 40 °C, dishwashing 55 °C), otherwise Tm (small tappings 25 °C, shower and cleaning 40 °C). Cold water 10 °C. Typical for a family; two baths."},
  "EN 16147 XL": {"group": "Standard test cycles", "cite": "Reg. (EU) 814/2013 / EN 16147", "ref": "Commission Regulation (EU) No 814/2013, Annex III, Table 1 (load profiles used for ecodesign and energy labelling; the same profiles are used in EN 16147 for heat pump water heaters).", "url": "https://eur-lex.europa.eu/eli/reg/2013/814/oj", "note": "Times, energies and flows as in the regulation. Energies are converted to litres at the use temperature: Tp where the table gives one (bath and floor cleaning 40 °C, dishwashing 55 °C), otherwise Tm (small tappings 25 °C, shower and cleaning 40 °C). Cold water 10 °C. Large family; three baths."},
  "IEA SHC Task 26, weekday": {"group": "Statistical profiles", "cite": "Jordan & Vajen (2001), IEA SHC Task 26", "ref": "Jordan, U., Vajen, K. (2001). Realistic domestic hot-water profiles in different time scales. IEA SHC Task 26, Universität Marburg.", "url": "https://sel.me.wisc.edu/trnsys/trnlib/iea-shc-task26/iea-shc-task26-load-profiles-description-jordan.pdf", "note": "200 L/day at 45 °C on average. Draw-off categories: short 1 L/min × 1 min (28/day), medium 6 L/min × 1 min (12/day), shower 8 L/min × 5 min (2/day), bath 14 L/min × 10 min (once a week). The original profile has random times; here short and medium draws are spread evenly from 05:00 to 23:00 and the showers are placed in the morning and evening peaks. Weekday without bath."},
  "IEA SHC Task 26, bath day": {"group": "Statistical profiles", "cite": "Jordan & Vajen (2001), IEA SHC Task 26", "ref": "Jordan, U., Vajen, K. (2001). Realistic domestic hot-water profiles in different time scales. IEA SHC Task 26, Universität Marburg.", "url": "https://sel.me.wisc.edu/trnsys/trnlib/iea-shc-task26/iea-shc-task26-load-profiles-description-jordan.pdf", "note": "200 L/day at 45 °C on average. Draw-off categories: short 1 L/min × 1 min (28/day), medium 6 L/min × 1 min (12/day), shower 8 L/min × 5 min (2/day), bath 14 L/min × 10 min (once a week). The original profile has random times; here short and medium draws are spread evenly from 05:00 to 23:00 and the showers are placed in the morning and evening peaks. Day with the weekly bath at 20:15."},
  "Danish house, 4 persons": {"group": "Measured in Danish houses", "cite": "Marszal-Pomianowska et al. (2021)", "ref": "Marszal-Pomianowska, A. et al. (2021). Comfort of domestic water in residential buildings: flow, temperature and energy in draw-off points. Field study in two Danish detached houses. Energies 14(11), 3314.", "url": "https://doi.org/10.3390/en14113314", "note": "House 1 in the study: 4 occupants, 92 L/day of hot water, 1.6 showers/day of 7–8 min at 35.5–40.4 °C, about 33 short kitchen draws/day (mostly under 20 s, 24.5 °C), hand washing about 23 °C, peaks 06:30–07:00 and 18:00–20:00 on weekdays. Representative weekday built from these statistics; the shower flow of 7 L/min is assumed."},
  "Danish house, 2 persons": {"group": "Measured in Danish houses", "cite": "Marszal-Pomianowska et al. (2021)", "ref": "Marszal-Pomianowska, A. et al. (2021). Comfort of domestic water in residential buildings: flow, temperature and energy in draw-off points. Field study in two Danish detached houses. Energies 14(11), 3314.", "url": "https://doi.org/10.3390/en14113314", "note": "House 2 in the study: 2 occupants, about 43 L/day of hot water, 0.8 showers/day, about 11 kitchen draws/day at 35.5 °C. Representative weekday built from these statistics; the shower flow of 7 L/min is assumed."},
  "Family of 4, morning and evening": {"group": "Illustrative (this book)", "cite": "illustrative, not from literature", "ref": "Illustrative profile written for this book, not taken from the literature.", "url": "", "note": "Shows the effect of when the showers are taken."},
  "Family of 4, all showers in the evening": {"group": "Illustrative (this book)", "cite": "illustrative, not from literature", "ref": "Illustrative profile written for this book, not taken from the literature.", "url": "", "note": "Shows the effect of when the showers are taken."},
  "Couple, morning showers": {"group": "Illustrative (this book)", "cite": "illustrative, not from literature", "ref": "Illustrative profile written for this book, not taken from the literature.", "url": "", "note": "Shows the effect of when the showers are taken."},
};
export const DEFAULT_PROFILE = "Family of 4, morning and evening";
// --- end of profiles ---

const DT = 10, RHO = 994, CP = 4182;

function tapDemand(tDay, p, profile) {
  // mean flow over the step starting at tDay; only the part of a tapping inside the step counts.
  // Tappings that share a step are added, with a flow-weighted use temperature.
  const stepH = DT / 3600;
  let fSum = 0, ftSum = 0;
  for (const [start, , vol0, flow, temp] of profile) {
    const vol = vol0 * (p.use_scale / 100), end = start + vol / flow / 60;
    const overlap = Math.min(tDay + stepH, end) - Math.max(tDay, start);
    if (overlap > 0) { const f = flow / 60 * overlap / stepH; fSum += f; ftSum += f * temp; }
  }
  return fSum > 0 ? [fSum, ftSum / fSum] : [0, null];
}

// DHWcalc output: a text file with one value per line, the draw-off flow in L/h for each time step,
// for a whole year (365 or 366 days) or a single day. The time step follows from the number of lines.
export function parseDhwcalc(text) {
  const flows = [];
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim(); if (!t) continue;
    const v = Number(t.split(/[\s;]+/).pop().replace(",", "."));
    if (Number.isFinite(v)) flows.push(Math.max(0, v));
  }
  const n = flows.length;
  for (const days of [365, 366, 1]) {
    if (n % days) continue;
    const spd = n / days, stepMin = 1440 / spd;
    if (Number.isInteger(stepMin) || Math.abs(stepMin - Math.round(stepMin)) < 1e-9) {
      const dailyL = [];
      for (let d = 0; d < days; d++) { let s = 0; for (let k = 0; k < spd; k++) s += flows[d * spd + k]; dailyL.push(s * stepMin / 60); }
      return { flows, days, spd, stepMin: Math.round(stepMin), dailyL };
    }
  }
  throw new Error(`Found ${n} values. A DHWcalc file has one flow value (L/h) per time step for 365 days (for example 525 600 lines at 1 min or 8 760 at 60 min) or for one day.`);
}

export function dhwcalcDay(data, day, tUse) {
  // one tapping per time step with flow; the volume is the flow (L/h) times the step length
  const taps = [], stepH = data.stepMin / 60;
  for (let k = 0; k < data.spd; k++) {
    const f = data.flows[day * data.spd + k];
    if (f > 0) taps.push([k * stepH, "DHWcalc", f * stepH, f / 60, tUse]);
  }
  return taps;
}

function cop(tSupply, p) {
  const tc = tSupply + 5 + 273.15, te = p.T_source - 5 + 273.15;
  return p.eta_carnot * tc / Math.max(tc - te, 1);
}

export function simulate(p = DEFAULTS, hours = Array(24).fill(true), profile = PROFILES[DEFAULT_PROFILE]) {
  const n = Math.round(p.n_layers);
  const mLayer = p.V_tank / 1000 * RHO / n, dz = p.H_tank / n, area = p.V_tank / 1000 / p.H_tank;
  const gCond = p.k_eff * area / dz, uaLayer = p.UA / n;
  const kIn = Math.min(n - 1, Math.max(0, Math.floor(n * (1 - p.inlet_pos / 100))));
  const kS = Math.min(n - 1, Math.max(0, Math.floor(n * (1 - p.sensor_pos / 100))));
  const T = new Float64Array(n).fill(p.T_set), dT = new Float64Array(n);
  let on = false, eStart = 0;
  const steps = Math.floor(p.days * 24 * 3600 / DT), rep0 = Math.floor((p.days - 1) * 24 * 3600 / DT);
  const out = { t: [], layers: [], t_tap: [], t_use: [], q_tap: [], q_hp: [], t_ch: [], cop: [], on: [], kIn, kS, n };
  const s = { tapped_kWh: 0, unmet_kWh: 0, unmet_min: 0, hp_kWh: 0, el_kWh: 0, loss_kWh: 0, starts: 0, run_h: 0 };
  for (let step = 0; step < steps; step++) {
    const t = step * DT / 3600, hour = Math.floor(t % 24);
    if (!hours[hour]) on = false;
    else if (!on && T[kS] < p.T_set - p.hyst) { on = true; if (step >= rep0) s.starts++; }
    else if (on && (T[kS] >= p.T_set || T[n - 1] >= p.T_hp_max - p.hex_approach - 1)) on = false;
    let mCh = 0, tCh = NaN, qHp = 0, c = NaN;
    if (on) {
      mCh = p.flow_ch / 60 / 1000 * RHO;
      const tBot = T[n - 1];
      const qMax = mCh * CP * (p.T_hp_max - p.hex_approach - tBot);
      qHp = Math.max(0, Math.min(p.P_hp * 1000, qMax));
      tCh = tBot + qHp / (mCh * CP);
      c = cop(tCh + p.hex_approach, p);
    }
    const [flow, tUse] = tapDemand(t % 24, p, profile);
    let mTap = 0, tTap = NaN, qTap = 0, qUnmet = 0;
    if (flow > 0) {
      const mMix = flow / 1000 * RHO;
      let frac;
      if (T[0] > tUse) { frac = (tUse - p.T_cold) / (T[0] - p.T_cold); tTap = tUse; }
      else { frac = 1; tTap = T[0]; }
      mTap = mMix * frac;
      qTap = mMix * CP * (tTap - p.T_cold);
      qUnmet = mMix * CP * (tUse - tTap);
    }
    dT.fill(0);
    for (let i = 0; i < n - 1; i++) {
      const fUp = mTap - (i >= kIn ? mCh : 0);
      if (fUp > 0) dT[i] += fUp * CP * (T[i + 1] - T[i]);
      else if (fUp < 0) dT[i + 1] += -fUp * CP * (T[i] - T[i + 1]);
      const q = gCond * (T[i + 1] - T[i]);
      dT[i] += q; dT[i + 1] -= q;
    }
    dT[n - 1] += mTap * CP * (p.T_cold - T[n - 1]);
    dT[kIn] += mCh * CP * ((on ? tCh : T[kIn]) - T[kIn]);
    let loss = 0;
    for (let i = 0; i < n; i++) {
      const ql = uaLayer * (T[i] - p.T_room);
      loss += ql;
      T[i] += DT * (dT[i] - ql) / (mLayer * CP);
    }
    let mixed = true;
    while (mixed) {
      mixed = false;
      for (let i = 0; i < n - 1; i++) {
        if (T[i + 1] > T[i] + 1e-9) {
          let j = i + 1;
          while (j + 1 < n && T[j + 1] > T[i]) j++;
          let sum = 0; for (let k = i; k <= j; k++) sum += T[k];
          const avg = sum / (j + 1 - i);
          for (let k = i; k <= j; k++) T[k] = avg;
          mixed = true;
        }
      }
    }
    if (step === rep0 - 1) { let e = 0; for (let i = 0; i < n; i++) e += T[i]; eStart = e * mLayer * CP / 3.6e6; }
    if (step >= rep0) {
      const h = DT / 3600 / 1000;
      s.tapped_kWh += qTap * h; s.unmet_kWh += qUnmet * h;
      if (qUnmet > 1e-6 && tTap < tUse - 1) s.unmet_min += DT / 60;
      s.hp_kWh += qHp * h;
      if (on && qHp > 0) { s.el_kWh += qHp / c * h; s.run_h += DT / 3600; }
      s.loss_kWh += loss * h;
      if ((step - rep0) % 6 === 0) {
        out.t.push(t - (p.days - 1) * 24); out.layers.push(Array.from(T));
        out.t_tap.push(flow > 0 ? tTap : NaN); out.t_use.push(flow > 0 ? tUse : NaN);
        out.q_tap.push(qTap / 1000); out.q_hp.push(qHp / 1000); out.t_ch.push(tCh); out.cop.push(c);
        out.on.push(on && qHp > 0);
      }
    }
  }
  s.cop_mean = s.el_kWh > 0 ? s.hp_kWh / s.el_kWh : NaN;
  s.T_top_end = T[0]; s.T_bot_end = T[n - 1];
  let eEnd = 0; for (let i = 0; i < n; i++) eEnd += T[i];
  s.stored_change_kWh = eEnd * mLayer * CP / 3.6e6 - eStart;   // closes the balance: hp = tapped + loss + change
  out.summary = s;
  return out;
}

// ---------------------------------------------------------------- user interface

const INPUTS = [
  ["Tank", [
    ["V_tank", "Volume", "L", 100, 500, 10, "Water volume of the tank."],
    ["H_tank", "Height", "m", 0.6, 2.0, 0.1, "Inner height of the tank. A tall, slim tank stratifies better than a short, wide one."],
    ["UA", "Heat loss coefficient UA", "W/K", 0.3, 4, 0.1, "Heat loss from the whole tank per K between the water and the room (20 °C). 1.2 W/K is about 45 W at 55 °C."],
    ["inlet_pos", "Charging inlet height", "% of height", 5, 95, 5, "Where the water from the heat exchanger enters the tank, measured from the bottom. The return to the heat exchanger is always at the bottom."],
    ["n_layers", "Number of layers", "", 5, 60, 1, "The model splits the tank into this many layers. Few layers smear out the thermocline (numerical mixing)."]]],
  ["Heat pump and heat exchanger", [
    ["P_hp", "Heat output", "kW", 1, 10, 0.5, "Heat output of the heat pump while it runs."],
    ["T_hp_max", "Max supply temperature", "°C", 50, 75, 1, "Highest supply temperature the heat pump can deliver. The heat output is reduced if it would be exceeded."],
    ["hex_approach", "Heat exchanger approach", "K", 1, 10, 0.5, "Temperature difference between the heat pump supply and the water returned to the tank. A bigger heat exchanger gives a smaller approach."],
    ["flow_ch", "Charging flow, tank side", "L/min", 0.5, 15, 0.5, "Flow from the bottom of the tank through the heat exchanger and back to the inlet. Low flow gives a large temperature rise in one pass."],
    ["T_source", "Source (outdoor air) temperature", "°C", -10, 20, 1, "Air temperature at the heat pump evaporator. Used for the COP."]]],
  ["Control", [
    ["T_set", "Setpoint", "°C", 40, 65, 1, "The heat pump stops when the sensor reaches this temperature."],
    ["hyst", "Start below setpoint by", "K", 1, 15, 0.5, "The heat pump starts when the sensor falls this far below the setpoint."],
    ["sensor_pos", "Sensor height", "% of height", 5, 95, 5, "Height of the tank sensor, measured from the bottom."]]],
  ["Tapping", [
    ["T_cold", "Cold water temperature", "°C", 5, 15, 0.5, "Temperature of the mains water entering at the bottom of the tank."],
    ["use_scale", "Hot water use", "% of profile", 50, 200, 10, "Scales the volume of every tapping in the selected profile."]]],
];

const COL = { top: "#b2182b", mid: "#e08214", bot: "#2166ac", ch: "#7b5ea7", tap: "#1a1a1a", use: "#5aa02c", hp: "#d0663a", draw: "#2b7bb9" };
const STOPS = [[10, [33, 102, 172]], [25, [146, 197, 222]], [40, [253, 219, 199]], [50, [239, 138, 98]], [60, [178, 24, 43]]];
function tColor(v) {
  if (!Number.isFinite(v)) return "#999";
  if (v <= STOPS[0][0]) return `rgb(${STOPS[0][1]})`;
  for (let i = 1; i < STOPS.length; i++) {
    const [t1, c1] = STOPS[i], [t0, c0] = STOPS[i - 1];
    if (v <= t1) { const f = (v - t0) / (t1 - t0); return `rgb(${c0.map((a, k) => Math.round(a + f * (c1[k] - a))).join(",")})`; }
  }
  return `rgb(${STOPS[STOPS.length - 1][1]})`;
}

const CSS = `
:host, .dt { --ink: #1f2328; --muted: #5f6770; --grid: #e3e6e8; --panel: #f6f8fa; --off: #fbe9e7; }
@media (prefers-color-scheme: dark) { :host, .dt { --ink: #e6edf3; --muted: #9aa4ae; --grid: #30363d; --panel: #161b22; --off: #3a1f1c; } }
.dt { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; font-size: 14px; color: var(--ink); }
.dt .controls { display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr)); gap: 12px; margin-bottom: 12px; }
.dt fieldset { min-width: 0; border: 1px solid var(--grid); border-radius: 8px; padding: 8px 12px 10px; margin: 0; background: var(--panel); }
.dt legend { font-weight: 600; padding: 0 4px; }
.dt label { display: grid; grid-template-columns: 1fr auto; gap: 2px 8px; margin-top: 6px; font-size: 13px; }
.dt label input { grid-column: 1 / 3; width: 100%; accent-color: #2b7bb9; }
.dt .help { color: var(--muted); cursor: help; font-size: 12px; }
.dt .val { font-variant-numeric: tabular-nums; color: var(--muted); }
.dt .bar { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; margin: 4px 0 8px; color: var(--muted); font-size: 13px; }
.dt button { font: inherit; padding: 4px 12px; border-radius: 6px; border: 1px solid var(--grid); background: var(--panel); color: var(--ink); cursor: pointer; }
.dt .hours { display: grid; grid-template-columns: repeat(8, minmax(0, 1fr)); gap: 3px; margin-top: 6px; }
.dt .hours button { padding: 3px 0; font-size: 12px; font-variant-numeric: tabular-nums; }
.dt .hours button.on { background: #2b7bb9; color: #fff; border-color: #2b7bb9; }
.dt select { font: inherit; font-size: 13px; width: 100%; margin-top: 6px; padding: 4px 6px; border-radius: 6px; border: 1px solid var(--grid); background: var(--panel); color: var(--ink); }
.dt .pinfo { margin-top: 6px; font-size: 12px; color: var(--muted); font-variant-numeric: tabular-nums; overflow-wrap: anywhere; }
.dt .tabs { display: flex; gap: 4px; border-bottom: 1px solid var(--grid); margin-bottom: 12px; }
.dt .tabs button { border-bottom: 0; border-radius: 6px 6px 0 0; padding: 6px 14px; }
.dt .tabs button.on { background: #2b7bb9; color: #fff; font-weight: 600; border-color: #2b7bb9; }
.dt .profctl { display: grid; grid-template-columns: minmax(0, 520px); margin-bottom: 12px; }
.dt .profpanel { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 12px; align-items: start; }
.dt .profpanel > .note, .dt .profpanel > h3 { grid-column: 1 / -1; margin: 4px 0 0; }
.dt .profpanel > .note { color: var(--muted); font-size: 13px; max-width: 75ch; }
.dt .profpanel h3 { font-size: 15px; }
.dt .pcard { min-width: 0; border: 1px solid var(--grid); border-radius: 8px; padding: 10px 12px; background: var(--panel); }
.dt .phead { display: flex; justify-content: space-between; align-items: center; gap: 8px; }
.dt .phead h4 { margin: 0; font-size: 14px; }
.dt .phead button { font-size: 12px; padding: 2px 8px; white-space: nowrap; }
.dt .pstats { margin: 4px 0 6px; font-size: 13px; color: var(--muted); font-variant-numeric: tabular-nums; }
.dt .pref, .dt .pnote { margin: 6px 0 0; font-size: 12px; line-height: 1.45; overflow-wrap: anywhere; }
.dt .pnote { color: var(--muted); }
.dt .pref a { color: #2b7bb9; }
.dt details { margin-top: 6px; font-size: 12px; }
.dt details summary { cursor: pointer; color: var(--muted); }
.dt details table { font-size: 12px; margin-top: 4px; }
.dt details th, .dt details td { padding: 3px 5px; }
.dt .file { display: block; margin-top: 6px; }
.dt .file input { position: absolute; opacity: 0; width: 1px; height: 1px; }
.dt .file span { display: inline-block; font-size: 13px; padding: 4px 12px; border-radius: 6px; border: 1px solid var(--grid); background: var(--panel); cursor: pointer; }
.dt .file input:focus-visible + span { outline: 2px solid #2b7bb9; }
.dt .impctl { display: grid; gap: 6px; margin-top: 6px; font-size: 13px; }
.dt .impctl label { display: inline; margin: 0; }
.dt .impctl .row { display: flex; gap: 6px; align-items: center; flex-wrap: wrap; }
.dt .impctl input[type=number] { width: 4.5em; font: inherit; padding: 2px 4px; background: transparent; color: var(--ink); border: 1px solid var(--grid); border-radius: 4px; }
.dt .impctl button { font-size: 12px; padding: 2px 8px; }
.dt .presets { display: flex; gap: 6px; flex-wrap: wrap; margin-top: 8px; }
.dt .presets button { font-size: 12px; padding: 2px 8px; }
.dt .viewer { display: grid; grid-template-columns: minmax(0, 3fr) minmax(0, 2fr); gap: 12px; align-items: start; }
@media (max-width: 640px) { .dt .viewer { grid-template-columns: minmax(0, 1fr); } }
.dt .time { display: flex; gap: 10px; align-items: center; margin: 6px 0 10px; }
.dt .time input { flex: 1; accent-color: #2b7bb9; }
.dt .time output { font-variant-numeric: tabular-nums; min-width: 4.5em; }
.dt .charts { display: grid; gap: 6px; }
.dt .legend { display: flex; gap: 14px; flex-wrap: wrap; font-size: 12px; margin: 2px 0 2px 46px; color: var(--muted); }
.dt .legend span { display: inline-flex; align-items: center; gap: 5px; }
.dt .legend svg { width: auto; flex: none; }
.dt table { border-collapse: collapse; width: 100%; font-size: 13px; font-variant-numeric: tabular-nums; }
.dt th, .dt td { padding: 4px 8px; border-bottom: 1px solid var(--grid); text-align: right; }
.dt th:first-child, .dt td:first-child { text-align: left; }
.dt .tablewrap { overflow-x: auto; }
.dt svg { width: 100%; height: auto; display: block; }
.dt svg text { fill: var(--ink); font-size: 11px; }
.dt svg .mut { fill: var(--muted); }
`;

function axis(arrays, floor0 = false) {
  let lo = Infinity, hi = -Infinity;
  for (const arr of arrays) for (const v of arr) if (Number.isFinite(v)) { if (v < lo) lo = v; if (v > hi) hi = v; }
  if (!Number.isFinite(lo)) { lo = 0; hi = 1; }
  if (floor0) lo = Math.min(lo, 0);
  if (hi - lo < 1e-6) { lo -= 0.5; hi += 0.5; }
  const raw = (hi - lo) / 5, mag = 10 ** Math.floor(Math.log10(raw));
  const step = [1, 2, 2.5, 5, 10].map(f => f * mag).find(st => st >= raw);
  const ymin = Math.floor(lo / step + 1e-9) * step, ymax = Math.ceil(hi / step - 1e-9) * step;
  const yticks = []; for (let v = ymin; v <= ymax + step / 2; v += step) yticks.push(+v.toFixed(6));
  return { ymin, ymax, yticks };
}

const W = 900, L = 46, R = 22, TM = 22, B = 30;
const X = v => L + v / 24 * (W - L - R);

function frame(H, opts, hours) {
  let s = "";
  hours.forEach((ok, h) => { if (!ok) s += `<rect x="${X(h)}" y="${TM}" width="${X(1) - X(0)}" height="${H - TM - B}" fill="var(--off)"/>`; });
  for (let v = 0; v <= 24; v += 3) s += `<line x1="${X(v)}" x2="${X(v)}" y1="${TM}" y2="${H - B}" stroke="var(--grid)"/><text x="${X(v)}" y="${H - B + 14}" text-anchor="middle" class="mut">${String(v).padStart(2, "0")}:00</text>`;
  s += `<text x="${L}" y="14" font-weight="600" style="font-size:12px">${opts.title}</text>`;
  s += `<text transform="translate(11 ${(TM + H - B) / 2}) rotate(-90)" text-anchor="middle" class="mut">${opts.ylabel}</text>`;
  return s;
}
const cursor = H => `<line class="cursor" x1="${X(0)}" x2="${X(0)}" y1="${TM}" y2="${H - B}" stroke="var(--ink)" stroke-width="1" stroke-dasharray="3 3"/>`;

function lineChart(series, opts, hours) {
  const H = opts.H || 200;
  const Y = v => TM + (opts.ymax - Math.min(opts.ymax, Math.max(opts.ymin, v))) / (opts.ymax - opts.ymin) * (H - TM - B);
  let s = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${opts.title}">` + frame(H, opts, hours);
  for (const v of opts.yticks) s += `<line x1="${L}" x2="${W - R}" y1="${Y(v)}" y2="${Y(v)}" stroke="var(--grid)"/><text x="${L - 6}" y="${Y(v) + 4}" text-anchor="end" class="mut">${v}</text>`;
  for (const sr of series) {
    let d = "", pen = false;
    for (let i = 0; i < sr.x.length; i++) {
      if (!Number.isFinite(sr.y[i])) { pen = false; continue; }
      d += `${pen ? "L" : "M"}${X(sr.x[i]).toFixed(1)} ${Y(sr.y[i]).toFixed(1)}`; pen = true;
    }
    if (sr.dots) for (let i = 0; i < sr.x.length; i += 1) if (Number.isFinite(sr.y[i])) d += `M${X(sr.x[i]).toFixed(1)} ${Y(sr.y[i]).toFixed(1)}h0.01`;
    s += `<path d="${d}" fill="none" stroke="${sr.color}" stroke-width="${sr.width || 1.8}" stroke-linecap="round" ${sr.dash ? `stroke-dasharray="${sr.dash}"` : ""}/>`;
  }
  return s + cursor(H) + "</svg>";
}

function heatmap(r, p, hours) {
  const H = 230, n = r.n, cols = 144, per = Math.round(r.t.length / cols);
  const Yh = z => TM + (1 - z) * (H - TM - B);              // z = height fraction 0..1
  let s = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Tank temperature over the day by height">` + frame(H, { title: "Tank temperature by height over the day [°C]", ylabel: "Height [m]" }, Array(24).fill(true));
  const cw = (X(24) - X(0)) / cols, lh = (H - TM - B) / n;
  for (let c = 0; c < cols; c++) {
    const row = r.layers[Math.min(r.layers.length - 1, c * per)];
    for (let i = 0; i < n; i++) s += `<rect x="${(X(0) + c * cw).toFixed(2)}" y="${(TM + i * lh).toFixed(2)}" width="${(cw + 0.6).toFixed(2)}" height="${(lh + 0.6).toFixed(2)}" fill="${tColor(row[i])}"/>`;
  }
  for (let k = 0; k <= 4; k++) { const z = k / 4; s += `<text x="${L - 6}" y="${Yh(z) + 4}" text-anchor="end" class="mut">${(z * p.H_tank).toFixed(1)}</text>`; }
  const zi = 1 - (r.kIn + 0.5) / n, zs = 1 - (r.kS + 0.5) / n;
  s += `<text x="${W - R - 2}" y="${Yh(zi) + 4}" text-anchor="end" style="font-size:10px" fill="#fff">inlet ◀</text>`;
  s += `<text x="${W - R - 2}" y="${Yh(zs) - 4}" text-anchor="end" style="font-size:10px" fill="#fff">sensor ◀</text>`;
  hours.forEach((ok, h) => { if (!ok) s += `<rect x="${X(h)}" y="${H - B + 1}" width="${X(1) - X(0)}" height="3" fill="${COL.hp}" opacity="0.5"/>`; });
  return s + cursor(H) + "</svg>";
}

function scaleBar() {
  let s = `<svg viewBox="0 0 ${W} 26"><defs><linearGradient id="dtg">`;
  for (const [t, c] of STOPS) s += `<stop offset="${(t - 10) / 50}" stop-color="rgb(${c})"/>`;
  s += `</linearGradient></defs><rect x="${L}" y="4" width="300" height="10" fill="url(#dtg)"/>`;
  for (const t of [10, 20, 30, 40, 50, 60]) s += `<text x="${L + (t - 10) / 50 * 300}" y="25" text-anchor="middle" class="mut">${t} °C</text>`;
  return s + `<text x="${L + 320}" y="13" class="mut">Shaded hours: heat pump not allowed to run</text></svg>`;
}

function schematic(r, p, idx) {
  const n = r.n, T = r.layers[idx], tx = 150, ty = 30, tw = 110, th = 280, lh = th / n;
  const yOf = k => ty + (k + 0.5) * lh;
  const yIn = yOf(r.kIn), yBot = ty + th - 6, yS = yOf(r.kS);
  const on = r.on[idx], tapping = Number.isFinite(r.t_tap[idx]);
  const pipe = (d, active, col) => `<path d="${d}" fill="none" stroke="${active ? col : "var(--grid)"}" stroke-width="${active ? 4 : 3}" stroke-linejoin="round"/>`;
  let s = `<svg viewBox="0 0 470 340" role="img" aria-label="Tank schematic at the selected time">`;
  for (let i = 0; i < n; i++) s += `<rect x="${tx}" y="${(ty + i * lh).toFixed(2)}" width="${tw}" height="${(lh + 0.5).toFixed(2)}" fill="${tColor(T[i])}"/>`;
  s += `<rect x="${tx}" y="${ty}" width="${tw}" height="${th}" fill="none" stroke="var(--ink)" stroke-width="2" rx="8"/>`;
  // tapping from the top, cold water in at the bottom
  s += pipe(`M${tx + tw / 2} ${ty} V12 H40`, tapping, COL.top);
  s += `<text x="40" y="8" class="mut">to taps</text>`;
  s += pipe(`M40 ${ty + th - 10} H${tx}`, tapping, COL.bot);
  s += `<text x="40" y="${ty + th + 6}" class="mut">cold water</text>`;
  // charging loop: bottom -> heat exchanger -> inlet
  const hx = 330, hy = 150, hw = 36, hh = 70;
  s += pipe(`M${tx + tw} ${yBot} H${hx + 10} V${hy + hh}`, on, COL.bot);
  s += pipe(`M${hx + 10} ${hy} V${yIn} H${tx + tw}`, on, COL.ch);
  s += `<rect x="${hx}" y="${hy}" width="${hw}" height="${hh}" fill="var(--panel)" stroke="var(--ink)" rx="3"/>`;
  s += `<path d="M${hx + 4} ${hy + 6} L${hx + hw - 4} ${hy + hh - 6} M${hx + hw - 4} ${hy + 6} L${hx + 4} ${hy + hh - 6}" stroke="var(--muted)"/>`;
  s += `<text x="${hx + hw / 2}" y="${hy + hh + 14}" text-anchor="middle" class="mut">heat exch.</text>`;
  // heat pump
  s += pipe(`M${hx + hw} ${hy + 14} H420`, on, COL.hp) + pipe(`M${hx + hw} ${hy + hh - 14} H420`, on, COL.bot);
  s += `<rect x="410" y="${hy - 10}" width="54" height="${hh + 20}" fill="var(--panel)" stroke="var(--ink)" rx="4"/>`;
  s += `<text x="437" y="${hy + hh / 2 - 4}" text-anchor="middle" style="font-weight:600">heat</text><text x="437" y="${hy + hh / 2 + 10}" text-anchor="middle" style="font-weight:600">pump</text>`;
  s += `<text x="437" y="${hy + hh + 26}" text-anchor="middle" style="font-weight:600" fill="${on ? COL.hp : "var(--muted)"}">${on ? `${r.q_hp[idx].toFixed(1)} kW` : "off"}</text>`;
  if (on) s += `<text x="437" y="${hy + hh + 40}" text-anchor="middle" class="mut">COP ${r.cop[idx].toFixed(1)}</text>`;
  // sensor and labels
  s += `<circle cx="${tx + 10}" cy="${yS}" r="4" fill="var(--ink)"/><text x="${tx - 6}" y="${yS + 4}" text-anchor="end" class="mut">sensor ${T[r.kS].toFixed(1)} °C</text>`;
  s += `<text x="${tx - 6}" y="${ty + 14}" text-anchor="end">top ${T[0].toFixed(1)} °C</text>`;
  s += `<text x="${tx - 6}" y="${ty + th - 26}" text-anchor="end">bottom ${T[n - 1].toFixed(1)} °C</text>`;
  if (on) s += `<text x="${tx + tw + 6}" y="${yIn - 6}" style="font-size:10px">${r.t_ch[idx].toFixed(1)} °C in</text>`;
  if (tapping) s += `<text x="40" y="24" style="font-weight:600">tap ${r.t_tap[idx].toFixed(1)} °C${r.t_tap[idx] < r.t_use[idx] - 0.05 ? ` (wants ${r.t_use[idx]})` : ""}</text>`;
  return s + "</svg>";
}

function profileHeat(prof, p) {
  const hourly = Array(24).fill(0);
  let vol = 0;
  for (const [t, , v, , tu] of prof) { const q = v * RHO / 1000 * CP * (tu - p.T_cold) / 3.6e6; hourly[Math.floor(t)] += q; vol += v; }
  return { hourly, vol, q: hourly.reduce((a, b) => a + b, 0) };
}

function miniBars(hourly, ymax) {
  const W2 = 480, H2 = 120, L2 = 30, B2 = 20, T2 = 8, R2 = 6, bw = (W2 - L2 - R2) / 24;
  const Y2 = v => T2 + (1 - v / ymax) * (H2 - T2 - B2);
  let s = `<svg viewBox="0 0 ${W2} ${H2}" role="img" aria-label="Heat drawn per hour">`;
  s += `<rect x="${L2 + 17 * bw}" y="${T2}" width="${4 * bw}" height="${H2 - T2 - B2}" fill="var(--off)"/>`;
  for (const v of [0, ymax / 2, ymax]) s += `<line x1="${L2}" x2="${W2 - R2}" y1="${Y2(v)}" y2="${Y2(v)}" stroke="var(--grid)"/><text x="${L2 - 4}" y="${Y2(v) + 4}" text-anchor="end" class="mut">${+v.toFixed(1)}</text>`;
  hourly.forEach((v, h) => { if (v > 0) s += `<rect x="${(L2 + h * bw + 1).toFixed(1)}" y="${Y2(Math.min(v, ymax)).toFixed(1)}" width="${(bw - 2).toFixed(1)}" height="${(Y2(0) - Y2(Math.min(v, ymax))).toFixed(1)}" fill="#2b7bb9"/>`; });
  for (let h = 0; h <= 24; h += 6) s += `<text x="${L2 + h * bw}" y="${H2 - 5}" text-anchor="middle" class="mut">${String(h).padStart(2, "0")}:00</text>`;
  return s + "</svg>";
}

function buildProfiles(panel, p, use) {
  const esc = t => String(t).replace(/&/g, "&amp;").replace(/</g, "&lt;");
  const all = Object.entries(PROFILES).map(([name, prof]) => [name, prof, profileHeat(prof, p)]);
  const ymax = Math.ceil(Math.max(...all.flatMap(([, , h]) => h.hourly)));
  let html = `<p class="note">Each profile is one day of tappings. The bars show the heat drawn per hour (kWh) with cold water at ${p.T_cold} °C; the shaded hours 17–21 are the evening price peak. Volumes are at the tap, after mixing to the use temperature.</p>`;
  let group = "";
  for (const [name, prof, h] of all) {
    const info = PROFILE_INFO[name];
    if (info.group !== group) { group = info.group; html += `<h3>${esc(group)}</h3>`; }
    const rows = prof.map(([t, n, v, f, tu]) => { const hh = Math.floor(t + 1e-9), mm = Math.round((t - hh) * 60); return `<tr><td>${String(hh).padStart(2, "0")}:${String(mm).padStart(2, "0")}</td><td>${esc(n)}</td><td>${v}</td><td>${f}</td><td>${tu}</td><td>${(v * RHO / 1000 * CP * (tu - p.T_cold) / 3.6e6).toFixed(3)}</td></tr>`; }).join("");
    html += `<section class="pcard"><div class="phead"><h4>${esc(name)}</h4><button type="button" data-use="${esc(name)}">Use in simulation</button></div>
      <p class="pstats">${h.q.toFixed(2)} kWh per day · ${h.vol.toFixed(0)} L at the tap · ${prof.length} tappings</p>
      ${miniBars(h.hourly, ymax)}
      <p class="pref">${info.url ? `${esc(info.ref)} <a href="${info.url}" target="_blank" rel="noopener">${esc(info.url.replace(/^https:\/\//, ""))}</a>` : esc(info.ref)}</p>
      <p class="pnote">${esc(info.note)}</p>
      <details><summary>Tappings</summary><div class="tablewrap"><table><thead><tr><th>Start</th><th>Tapping</th><th>L</th><th>L/min</th><th>°C</th><th>kWh</th></tr></thead><tbody>${rows}</tbody></table></div></details>
    </section>`;
  }
  panel.innerHTML = html;
  panel.querySelectorAll("button[data-use]").forEach(b => b.addEventListener("click", () => use(b.dataset.use)));
}

function render({ model, el }) {
  const p = { ...DEFAULTS };
  for (const key of Object.keys(DEFAULTS)) { const v = model.get(key); if (typeof v === "number") p[key] = v; }
  let hours = Array(24).fill(true), profileName = DEFAULT_PROFILE, tapSel = null;
  const root = document.createElement("div"); root.className = "dt";
  const style = document.createElement("style"); style.textContent = CSS;
  el.appendChild(style); el.appendChild(root);
  const tabs = document.createElement("div"); tabs.className = "tabs"; tabs.setAttribute("role", "tablist");
  const sim = document.createElement("div"), profPanel = document.createElement("div");
  const profCtl = document.createElement("div"), profList = document.createElement("div");
  profCtl.className = "profctl"; profList.className = "profpanel"; profPanel.hidden = true;
  profPanel.append(profCtl, profList);
  root.append(tabs, sim, profPanel);
  for (const [label, panel] of [["Simulation", sim], ["Tapping profiles", profPanel]]) {
    const b = document.createElement("button"); b.type = "button"; b.textContent = label; b.setAttribute("role", "tab");
    b.addEventListener("click", () => showTab(panel));
    tabs.appendChild(b);
  }
  function rebuildProfiles() { buildProfiles(profList, p, name => { sliders._profile.select(name); showTab(sim); }); }
  function showTab(panel) {
    sim.hidden = panel !== sim; profPanel.hidden = panel !== profPanel;
    tabs.querySelectorAll("button").forEach((x, i) => { const on = (i === 0) === (panel === sim); x.classList.toggle("on", on); x.setAttribute("aria-selected", on); });
  }

  const controls = document.createElement("div"); controls.className = "controls";
  const sliders = {};
  for (const [group, items] of INPUTS) {
    const fs = document.createElement("fieldset");
    fs.innerHTML = `<legend>${group}</legend>`;
    for (const [key, label, unit, min, max, step, help] of items) {
      const lab = document.createElement("label");
      lab.title = help;
      lab.innerHTML = `<span>${label} <span class="help" aria-label="${help}">ⓘ</span></span><span class="val"></span><input type="range" min="${min}" max="${max}" step="${step}" value="${p[key]}">`;
      const input = lab.querySelector("input"), val = lab.querySelector(".val");
      const show = () => { val.textContent = `${(+input.value).toLocaleString("en", { maximumFractionDigits: 2 })} ${unit}`; };
      input.addEventListener("input", () => { p[key] = +input.value; show(); sliders._profile?.refresh(); schedule(); });
      show(); sliders[key] = { input, show };
      fs.appendChild(lab);
    }
    if (group === "Tapping") {
      const wrap = document.createElement("div");
      wrap.innerHTML = `<div style="margin-top:10px;font-size:13px">Tapping profile <span class="help" title="Predefined days of hot water use. The heat-flow graph shows each tapping.">ⓘ</span></div>`;
      const sel = document.createElement("select"); sel.id = "dt-profile"; sel.setAttribute("aria-label", "Tapping profile");
      const groups = {};
      for (const name of Object.keys(PROFILES)) {
        const g = PROFILE_INFO[name].group;
        if (!groups[g]) { groups[g] = document.createElement("optgroup"); groups[g].label = g; sel.appendChild(groups[g]); }
        const o = document.createElement("option"); o.value = o.textContent = name; groups[g].appendChild(o);
      }
      sel.addEventListener("change", () => { profileName = sel.value; markProfile(); schedule(); });
      const info = document.createElement("div"); info.className = "pinfo";
      const markProfile = () => {
        sel.value = profileName;
        const prof = PROFILES[profileName];
        const q = prof.reduce((a, [, , v, , tu]) => a + v * (p.use_scale / 100) * RHO / 1000 * CP * (tu - p.T_cold), 0) / 3.6e6;
        info.textContent = `${prof.length} tappings, ${q.toFixed(1)} kWh per day. Source: ${PROFILE_INFO[profileName].cite}.`;
      };
      // DHWcalc import
      const imp = document.createElement("div"); imp.className = "import";
      imp.innerHTML = `<div style="margin-top:10px;font-size:13px">Import a DHWcalc profile <span class="help" title="DHWcalc writes one flow value (L/h) per line for every time step of a year. Pick one day of the file; it is repeated every simulated day.">ⓘ</span></div>
        <label class="file"><input type="file" id="dt-dhwcalc" accept=".txt,.csv,.dat,text/plain"><span>Choose DHWcalc file…</span></label>
        <div class="impctl" hidden>
          <div class="row"><label for="dt-day">Day of year</label><input type="number" id="dt-day" min="1" max="365" step="1" value="1"></div>
          <div class="row"><button type="button" data-pick="median">Median day</button><button type="button" data-pick="max">Busiest day</button><button type="button" data-pick="min">Quietest day</button></div>
          <div class="row"><label for="dt-tuse">Draw-off temperature</label><input type="number" id="dt-tuse" min="25" max="65" step="1" value="45"><span>°C</span></div>
        </div>
        <div class="pinfo imsg" role="status"></div>`;
      const fileIn = imp.querySelector("#dt-dhwcalc"), ctl = imp.querySelector(".impctl"), dayIn = imp.querySelector("#dt-day"),
            tIn = imp.querySelector("#dt-tuse"), msg = imp.querySelector(".imsg");
      let data = null, fileName = "";
      const IMP = "DHWcalc import";
      function applyImport() {
        if (!data) return;
        const day = Math.min(data.days, Math.max(1, Math.round(+dayIn.value || 1))) - 1, tUse = +tIn.value || 45;
        dayIn.value = day + 1;
        PROFILES[IMP] = dhwcalcDay(data, day, tUse);
        const yearL = data.dailyL.reduce((a, b) => a + b, 0);
        PROFILE_INFO[IMP] = { group: "Imported", cite: `DHWcalc file ${fileName}, day ${day + 1}`,
          ref: "Jordan, U., Vajen, K. (2005). DHWcalc: program to generate domestic hot water profiles with statistical means for user defined conditions. Proc. ISES Solar World Congress, Orlando. Software: Universität Kassel.",
          url: "https://www.uni-kassel.de/maschinenbau/en/institute/thermische-energietechnik/fachgebiete/solar-und-anlagentechnik/downloads.html",
          note: `File ${fileName}: ${data.days} day(s) at ${data.stepMin} min time step, mean ${(yearL / data.days).toFixed(0)} L/day. Day ${day + 1} draws ${data.dailyL[day].toFixed(0)} L. Each time step with flow becomes one tapping at ${tUse} °C (the file itself has no temperature).` };
        if (!groups.Imported) { groups.Imported = document.createElement("optgroup"); groups.Imported.label = "Imported"; sel.prepend(groups.Imported); }
        if (!groups.Imported.querySelector("option")) { const o = document.createElement("option"); o.value = o.textContent = IMP; groups.Imported.appendChild(o); }
        msg.textContent = `Loaded ${fileName}: ${data.days} days, ${data.stepMin} min steps, mean ${(yearL / data.days).toFixed(0)} L/day. Day ${day + 1}: ${data.dailyL[day].toFixed(0)} L.`;
        profileName = IMP; markProfile(); rebuildProfiles(); schedule();
      }
      fileIn.addEventListener("change", async () => {
        const f = fileIn.files[0]; if (!f) return;
        try {
          data = parseDhwcalc(await f.text()); fileName = f.name;
          dayIn.max = data.days; ctl.hidden = false;
          const order = data.dailyL.map((v, i) => i).sort((a, b) => data.dailyL[a] - data.dailyL[b]);
          dayIn.value = order[Math.floor(data.days / 2)] + 1;
          applyImport();
        } catch (e) { msg.textContent = `Could not read ${f.name}. ${e.message}`; }
      });
      dayIn.addEventListener("change", applyImport); tIn.addEventListener("change", applyImport);
      imp.querySelectorAll("button[data-pick]").forEach(b => b.addEventListener("click", () => {
        if (!data) return;
        const order = data.dailyL.map((v, i) => i).sort((a, c) => data.dailyL[a] - data.dailyL[c]);
        dayIn.value = 1 + (b.dataset.pick === "max" ? order[order.length - 1] : b.dataset.pick === "min" ? order[0] : order[Math.floor(data.days / 2)]);
        applyImport();
      }));
      // the Simulation tab gets only the dropdown; the rest of this group goes to the Tapping profiles tab
      const selFs = document.createElement("fieldset");
      selFs.innerHTML = `<legend>Tapping profile</legend>`;
      selFs.appendChild(sel);
      sel.removeAttribute("aria-label"); sel.setAttribute("aria-label", "Tapping profile");
      tapSel = selFs;
      wrap.querySelector("div").textContent = "Selected profile";
      wrap.append(info, imp); fs.appendChild(wrap);
      fs.querySelector("legend").textContent = "Tapping settings";
      markProfile();
      sliders._profile = { reset: () => { profileName = DEFAULT_PROFILE; markProfile(); }, refresh: markProfile, select: name => { profileName = name; markProfile(); schedule(); } };
    }
    if (group === "Control") {
      const wrap = document.createElement("div");
      wrap.innerHTML = `<div style="margin-top:8px;font-size:13px">Hours the heat pump may run <span class="help" title="Click an hour to block or allow it. Blocked hours are shaded in the graphs.">ⓘ</span></div>`;
      const grid = document.createElement("div"); grid.className = "hours";
      const btns = hours.map((_, h) => {
        const b = document.createElement("button"); b.textContent = String(h).padStart(2, "0");
        b.title = `${String(h).padStart(2, "0")}:00–${String(h + 1).padStart(2, "0")}:00`;
        b.addEventListener("click", () => { hours[h] = !hours[h]; markHours(); schedule(); });
        grid.appendChild(b); return b;
      });
      const markHours = () => btns.forEach((b, h) => { b.classList.toggle("on", hours[h]); b.setAttribute("aria-pressed", hours[h]); });
      const presets = document.createElement("div"); presets.className = "presets";
      for (const [lab, fn] of [["All hours", h => true], ["Not 17–21", h => h < 17 || h >= 21], ["Night 00–06", h => h < 6], ["Night + midday", h => h < 6 || (h >= 11 && h < 15)]]) {
        const b = document.createElement("button"); b.textContent = lab;
        b.addEventListener("click", () => { hours = hours.map((_, h) => fn(h)); markHours(); schedule(); });
        presets.appendChild(b);
      }
      wrap.append(grid, presets); fs.appendChild(wrap);
      markHours();
      sliders._hours = { reset: () => { hours = Array(24).fill(true); markHours(); } };
    }
    if (group === "Tapping") { controls.appendChild(tapSel); profCtl.appendChild(fs); }
    else controls.appendChild(fs);
  }
  sim.appendChild(controls);

  const bar = document.createElement("div"); bar.className = "bar";
  const reset = document.createElement("button"); reset.textContent = "Reset to defaults";
  const status = document.createElement("span");
  bar.append(reset, status); sim.appendChild(bar);
  reset.addEventListener("click", () => {
    Object.assign(p, DEFAULTS);
    for (const [key, sl] of Object.entries(sliders)) { if (key.startsWith("_")) sl.reset(); else { sl.input.value = p[key]; sl.show(); } }
    schedule();
  });

  const viewer = document.createElement("div"); viewer.className = "viewer";
  const schem = document.createElement("div"), profile = document.createElement("div");
  viewer.append(schem, profile);
  const time = document.createElement("div"); time.className = "time";
  time.innerHTML = `<button type="button">▶ Play</button><input type="range" min="0" max="1439" step="1" value="1170" aria-label="Time of day"><output></output>`;
  const play = time.querySelector("button"), tSlider = time.querySelector("input"), tOut = time.querySelector("output");
  const charts = document.createElement("div"); charts.className = "charts";
  const tableWrap = document.createElement("div"); tableWrap.className = "tablewrap";
  sim.append(viewer, time, charts, tableWrap);
  rebuildProfiles();
  showTab(sim);

  let res = null, timerId = null, anim = null;
  function profileChart(idx) {
    const n = res.n, T = res.layers[idx], H = 340, Lp = 44, Rp = 10, Tp = 30, Bp = 30, Wp = 300;
    const ax = axis([[p.T_cold, p.T_set, ...T]]);
    const Xp = v => Lp + (v - ax.ymin) / (ax.ymax - ax.ymin) * (Wp - Lp - Rp), Yp = z => Tp + (1 - z) * (H - Tp - Bp);
    let s = `<svg viewBox="0 0 ${Wp} ${H}" role="img" aria-label="Temperature profile in the tank">`;
    s += `<text x="${Lp}" y="14" font-weight="600" style="font-size:12px">Temperature profile</text>`;
    for (const v of ax.yticks) s += `<line x1="${Xp(v)}" x2="${Xp(v)}" y1="${Tp}" y2="${H - Bp}" stroke="var(--grid)"/><text x="${Xp(v)}" y="${H - Bp + 14}" text-anchor="middle" class="mut">${v}</text>`;
    for (let k = 0; k <= 4; k++) { const z = k / 4; s += `<line x1="${Lp}" x2="${Wp - Rp}" y1="${Yp(z)}" y2="${Yp(z)}" stroke="var(--grid)"/><text x="${Lp - 6}" y="${Yp(z) + 4}" text-anchor="end" class="mut">${(z * p.H_tank).toFixed(1)}</text>`; }
    s += `<text x="${(Lp + Wp - Rp) / 2}" y="${H - 4}" text-anchor="middle" class="mut">Temperature [°C]</text>`;
    s += `<text transform="translate(11 ${(Tp + H - Bp) / 2}) rotate(-90)" text-anchor="middle" class="mut">Height [m]</text>`;
    s += `<line x1="${Xp(p.T_set)}" x2="${Xp(p.T_set)}" y1="${Tp}" y2="${H - Bp}" stroke="${COL.use}" stroke-dasharray="3 3"/><text x="${Xp(p.T_set) - 3}" y="${Tp - 4}" text-anchor="end" style="font-size:10px" class="mut">setpoint</text>`;
    let d = "";
    for (let i = 0; i < n; i++) { const z = 1 - (i + 0.5) / n; d += `${i ? "L" : "M"}${Xp(T[i]).toFixed(1)} ${Yp(z).toFixed(1)}`; }
    s += `<path d="${d}" fill="none" stroke="var(--ink)" stroke-width="2"/>`;
    const zi = 1 - (res.kIn + 0.5) / n;
    s += `<line x1="${Lp}" x2="${Lp + 10}" y1="${Yp(zi)}" y2="${Yp(zi)}" stroke="${COL.ch}" stroke-width="3"/><text x="${Lp + 14}" y="${Yp(zi) + 4}" style="font-size:10px" fill="${COL.ch}">inlet</text>`;
    return s + "</svg>";
  }
  function showTime() {
    if (!res) return;
    const idx = Math.min(res.t.length - 1, +tSlider.value);
    const hh = Math.floor(idx / 60), mm = idx % 60;
    tOut.textContent = `${String(hh).padStart(2, "0")}:${String(mm).padStart(2, "0")}`;
    schem.innerHTML = schematic(res, p, idx);
    profile.innerHTML = profileChart(idx);
    const x = X(idx / 60);
    charts.querySelectorAll(".cursor").forEach(c => { c.setAttribute("x1", x); c.setAttribute("x2", x); });
  }
  tSlider.addEventListener("input", showTime);
  play.addEventListener("click", () => {
    if (anim) { clearInterval(anim); anim = null; play.textContent = "▶ Play"; return; }
    play.textContent = "❚❚ Pause";
    anim = setInterval(() => { tSlider.value = (+tSlider.value + 5) % 1440; showTime(); }, 40);
  });

  function legend(items) {
    return `<div class="legend">${items.map(([lab, col, dash]) => `<span><svg width="24" height="10"><line x1="0" x2="24" y1="5" y2="5" stroke="${col}" stroke-width="2.2" ${dash ? `stroke-dasharray="${dash}"` : ""}/></svg>${lab}</span>`).join("")}</div>`;
  }
  function schedule() { clearTimeout(timerId); status.textContent = "calculating…"; timerId = setTimeout(run, 120); }
  function run() {
    const t0 = performance.now();
    res = simulate(p, hours, PROFILES[profileName]);
    const r = res, n = r.n;
    const col = k => r.layers.map(T => T[k]);
    let html = heatmap(r, p, hours) + scaleBar();
    const tS = [
      { x: r.t, y: col(0), color: COL.top }, { x: r.t, y: col(r.kIn), color: COL.mid }, { x: r.t, y: col(n - 1), color: COL.bot },
      { x: r.t, y: r.t_ch, color: COL.ch, width: 1.4 },
      { x: r.t, y: r.t_use, color: COL.use, width: 5 }, { x: r.t, y: r.t_tap, color: COL.tap, width: 2.4 },
    ];
    html += legend([["Top", COL.top], ["At the inlet", COL.mid], ["Bottom", COL.bot], ["Water from heat exchanger", COL.ch], ["Wanted at tap", COL.use], ["Delivered at tap", COL.tap]]);
    html += lineChart(tS, { title: "Temperatures [°C]", ylabel: "°C", ...axis([...tS.map(x => x.y), [p.T_cold]]) }, hours);
    const pS = [{ x: r.t, y: r.q_tap, color: COL.draw, width: 1.2 }, { x: r.t, y: r.q_hp, color: COL.hp }];
    html += legend([["Heat drawn at the taps", COL.draw], ["Heat pump output", COL.hp]]);
    html += lineChart(pS, { title: "Heat flow [kW]", ylabel: "kW", H: 180, ...axis(pS.map(x => x.y), true) }, hours);
    charts.innerHTML = html;
    const s = r.summary, f = (v, d = 2) => Number.isFinite(v) ? v.toFixed(d) : "–";
    tableWrap.innerHTML = `<table><thead><tr><th>Last of ${p.days} identical days</th><th>Value</th></tr></thead><tbody>
      <tr><td>Heat delivered at the taps</td><td>${f(s.tapped_kWh)} kWh</td></tr>
      <tr><td title="Heat missing because the tank top was colder than the use temperature">Heat not delivered (too cold)</td><td>${f(s.unmet_kWh)} kWh, ${f(s.unmet_min, 0)} min</td></tr>
      <tr><td>Heat from the heat pump</td><td>${f(s.hp_kWh)} kWh</td></tr>
      <tr><td>Heat loss from the tank</td><td>${f(s.loss_kWh)} kWh</td></tr>
      <tr><td title="Heat stored in the tank at midnight minus the previous midnight. Heat pump = taps + loss + change.">Change in stored heat</td><td>${f(s.stored_change_kWh)} kWh</td></tr>
      <tr><td>Electricity for the heat pump</td><td>${f(s.el_kWh)} kWh</td></tr>
      <tr><td>Mean COP</td><td>${f(s.cop_mean)}</td></tr>
      <tr><td>Heat pump starts / run time</td><td>${s.starts} / ${f(s.run_h, 1)} h</td></tr>
      </tbody></table>`;
    status.textContent = `Calculated in ${Math.round(performance.now() - t0)} ms.`;
    showTime();
  }
  run();
  return () => { clearTimeout(timerId); clearInterval(anim); };
}

export default { render };
