"""Stratified hot water tank charged by a heat pump through an external heat exchanger.

This is the reference model behind the interactive app in the domestic hot water chapter
(dhw-tank.mjs runs the same model in the browser).

Layout:
- The tank is split into N horizontal layers of equal volume (layer 0 at the top).
- Charging loop: a pump draws water from the bottom of the tank, the heat exchanger heats it,
  and it returns to the layer at mid-height (inlet height adjustable).
- Tapping: hot water leaves at the top, and the same flow of cold mains water enters at the bottom.
  A thermostatic mixer at the tap mixes hot and cold water to the use temperature.
  If the top of the tank is colder than the use temperature, the tap gets tank water as it is.
- No circulation loop.

Physics per layer (explicit Euler, time step DT):
- Advection between layers with upwind differencing. The net flow across an interface is
  the tapping flow (upwards) minus the charging flow (downwards, only below the inlet).
- Vertical conduction with an effective conductivity (water plus tank wall).
- Heat loss to the room through UA, shared between layers by volume.
- Buoyancy: if a layer is warmer than the layer above it, the two are mixed. This is
  repeated until the tank is stable, so hot water entering at mid-height rises to its own level.

Heat pump and heat exchanger:
- The heat pump delivers its rated heat output, unless that would push its supply temperature
  above the maximum. The heat exchanger has a fixed approach: the water returned to the tank is
  `hex_approach` K colder than the heat pump supply.
- COP = eta_carnot * T_cond / (T_cond - T_evap), with T_cond = heat pump supply + 5 K
  and T_evap = source (outdoor air) temperature - 5 K.

Control:
- The heat pump starts when the sensor layer is below setpoint - hysteresis and stops when it
  reaches the setpoint. It also stops (high-temperature cut-out) when the water from the bottom
  of the tank is within 1 K of the highest temperature the heat exchanger can deliver.
  It only runs in the allowed hours.

Run:  python dhw_tank.py
"""
import math

DEFAULTS = dict(
    V_tank=200.0,        # tank volume, L
    H_tank=1.2,          # tank height, m
    n_layers=30,         # number of layers
    UA=1.2,              # heat loss coefficient of the tank, W/K
    T_room=20.0,         # temperature around the tank, C
    k_eff=1.5,           # effective vertical conductivity, water + wall, W/(m K)
    inlet_pos=50.0,      # charging inlet height, % of tank height from the bottom
    P_hp=3.0,            # heat pump heat output, kW
    T_hp_max=65.0,       # maximum heat pump supply temperature, C
    hex_approach=5.0,    # heat exchanger approach, K
    flow_ch=2.0,         # charging flow on the tank side, L/min
    T_source=7.0,        # heat pump source (outdoor air) temperature, C
    eta_carnot=0.5,      # Carnot efficiency of the heat pump
    T_set=55.0,          # setpoint at the sensor, C
    hyst=5.0,            # start at T_set - hyst, K
    sensor_pos=60.0,     # sensor height, % of tank height from the bottom
    T_cold=10.0,         # cold mains water, C
    use_scale=100.0,     # tapping volumes in % of the default profile
    days=3,              # days simulated; the last day is reported
)
ALL_HOURS = [True] * 24

# Tapping profiles: (start time h, name, volume at the tap L, flow at the tap L/min, use temperature C).
# PROFILE_INFO holds the group, the literature reference and how each profile was built.
# --- profiles (generated by build_profiles.py) ---
PROFILES = {
    'EN 16147 M': [(7.0, 'small', 6.1, 3, 25), (7.083333333333333, 'shower', 40.4, 6, 40), (7.5, 'small', 6.1, 3, 25), (8.016666666666667, 'small', 6.1, 3, 25), (8.25, 'small', 6.1, 3, 25), (8.5, 'small', 6.1, 3, 25), (8.75, 'small', 6.1, 3, 25), (9.0, 'small', 6.1, 3, 25), (9.5, 'small', 6.1, 3, 25), (10.5, 'floor cleaning', 3.0, 3, 40), (11.5, 'small', 6.1, 3, 25), (11.75, 'small', 6.1, 3, 25), (12.75, 'dishwashing', 6.1, 4, 55), (14.5, 'small', 6.1, 3, 25), (15.5, 'small', 6.1, 3, 25), (16.5, 'small', 6.1, 3, 25), (18.0, 'small', 6.1, 3, 25), (18.25, 'cleaning', 3.0, 3, 40), (18.5, 'cleaning', 3.0, 3, 40), (19.0, 'small', 6.1, 3, 25), (20.5, 'dishwashing', 14.1, 4, 55), (21.25, 'small', 6.1, 3, 25), (21.5, 'shower', 40.4, 6, 40)],
    'EN 16147 L': [(7.0, 'small', 6.1, 3, 25), (7.083333333333333, 'shower', 40.4, 6, 40), (7.5, 'small', 6.1, 3, 25), (7.75, 'small', 6.1, 3, 25), (8.083333333333334, 'bath', 104.1, 10, 40), (8.416666666666666, 'small', 6.1, 3, 25), (8.5, 'small', 6.1, 3, 25), (8.75, 'small', 6.1, 3, 25), (9.0, 'small', 6.1, 3, 25), (9.5, 'small', 6.1, 3, 25), (10.5, 'floor cleaning', 3.0, 3, 40), (11.5, 'small', 6.1, 3, 25), (11.75, 'small', 6.1, 3, 25), (12.75, 'dishwashing', 6.1, 4, 55), (14.5, 'small', 6.1, 3, 25), (15.5, 'small', 6.1, 3, 25), (16.5, 'small', 6.1, 3, 25), (18.0, 'small', 6.1, 3, 25), (18.25, 'cleaning', 3.0, 3, 40), (18.5, 'cleaning', 3.0, 3, 40), (19.0, 'small', 6.1, 3, 25), (20.5, 'dishwashing', 14.1, 4, 55), (20.766666666666666, 'bath', 104.1, 10, 40), (21.5, 'small', 6.1, 3, 25)],
    'EN 16147 XL': [(7.0, 'small', 6.1, 3, 25), (7.25, 'shower', 52.5, 6, 40), (7.433333333333334, 'small', 6.1, 3, 25), (7.75, 'bath', 127.6, 10, 40), (8.016666666666667, 'small', 6.1, 3, 25), (8.25, 'small', 6.1, 3, 25), (8.5, 'small', 6.1, 3, 25), (8.75, 'small', 6.1, 3, 25), (9.0, 'small', 6.1, 3, 25), (9.5, 'small', 6.1, 3, 25), (10.0, 'small', 6.1, 3, 25), (10.5, 'floor cleaning', 3.0, 3, 40), (11.0, 'small', 6.1, 3, 25), (11.5, 'small', 6.1, 3, 25), (11.75, 'small', 6.1, 3, 25), (12.75, 'dishwashing', 14.1, 4, 55), (14.5, 'small', 6.1, 3, 25), (15.0, 'small', 6.1, 3, 25), (15.5, 'small', 6.1, 3, 25), (16.0, 'small', 6.1, 3, 25), (16.5, 'small', 6.1, 3, 25), (17.0, 'small', 6.1, 3, 25), (18.0, 'small', 6.1, 3, 25), (18.25, 'cleaning', 3.0, 3, 40), (18.5, 'cleaning', 3.0, 3, 40), (19.0, 'small', 6.1, 3, 25), (20.5, 'dishwashing', 14.1, 4, 55), (20.766666666666666, 'bath', 127.6, 10, 40), (21.25, 'small', 6.1, 3, 25), (21.5, 'bath', 127.6, 10, 40)],
    'IEA SHC Task 26, weekday': [(5.321428571428571, 'short', 1, 1, 45), (5.45, 'medium', 6, 6, 45), (5.964285714285714, 'short', 1, 1, 45), (6.607142857142858, 'short', 1, 1, 45), (6.95, 'medium', 6, 6, 45), (7.0, 'shower', 40, 8, 45), (7.25, 'short', 1, 1, 45), (7.892857142857142, 'short', 1, 1, 45), (8.45, 'medium', 6, 6, 45), (8.535714285714285, 'short', 1, 1, 45), (9.178571428571429, 'short', 1, 1, 45), (9.821428571428571, 'short', 1, 1, 45), (9.95, 'medium', 6, 6, 45), (10.464285714285715, 'short', 1, 1, 45), (11.107142857142858, 'short', 1, 1, 45), (11.45, 'medium', 6, 6, 45), (11.75, 'short', 1, 1, 45), (12.392857142857142, 'short', 1, 1, 45), (12.95, 'medium', 6, 6, 45), (13.035714285714286, 'short', 1, 1, 45), (13.678571428571429, 'short', 1, 1, 45), (14.321428571428571, 'short', 1, 1, 45), (14.45, 'medium', 6, 6, 45), (14.964285714285714, 'short', 1, 1, 45), (15.607142857142858, 'short', 1, 1, 45), (15.950000000000001, 'medium', 6, 6, 45), (16.25, 'short', 1, 1, 45), (16.892857142857142, 'short', 1, 1, 45), (17.450000000000003, 'medium', 6, 6, 45), (17.535714285714285, 'short', 1, 1, 45), (18.17857142857143, 'short', 1, 1, 45), (18.82142857142857, 'short', 1, 1, 45), (18.950000000000003, 'medium', 6, 6, 45), (19.464285714285715, 'short', 1, 1, 45), (19.5, 'shower', 40, 8, 45), (20.107142857142858, 'short', 1, 1, 45), (20.450000000000003, 'medium', 6, 6, 45), (20.75, 'short', 1, 1, 45), (21.392857142857142, 'short', 1, 1, 45), (21.95, 'medium', 6, 6, 45), (22.035714285714285, 'short', 1, 1, 45), (22.678571428571427, 'short', 1, 1, 45)],
    'IEA SHC Task 26, bath day': [(5.321428571428571, 'short', 1, 1, 45), (5.45, 'medium', 6, 6, 45), (5.964285714285714, 'short', 1, 1, 45), (6.607142857142858, 'short', 1, 1, 45), (6.95, 'medium', 6, 6, 45), (7.0, 'shower', 40, 8, 45), (7.25, 'short', 1, 1, 45), (7.892857142857142, 'short', 1, 1, 45), (8.45, 'medium', 6, 6, 45), (8.535714285714285, 'short', 1, 1, 45), (9.178571428571429, 'short', 1, 1, 45), (9.821428571428571, 'short', 1, 1, 45), (9.95, 'medium', 6, 6, 45), (10.464285714285715, 'short', 1, 1, 45), (11.107142857142858, 'short', 1, 1, 45), (11.45, 'medium', 6, 6, 45), (11.75, 'short', 1, 1, 45), (12.392857142857142, 'short', 1, 1, 45), (12.95, 'medium', 6, 6, 45), (13.035714285714286, 'short', 1, 1, 45), (13.678571428571429, 'short', 1, 1, 45), (14.321428571428571, 'short', 1, 1, 45), (14.45, 'medium', 6, 6, 45), (14.964285714285714, 'short', 1, 1, 45), (15.607142857142858, 'short', 1, 1, 45), (15.950000000000001, 'medium', 6, 6, 45), (16.25, 'short', 1, 1, 45), (16.892857142857142, 'short', 1, 1, 45), (17.450000000000003, 'medium', 6, 6, 45), (17.535714285714285, 'short', 1, 1, 45), (18.17857142857143, 'short', 1, 1, 45), (18.82142857142857, 'short', 1, 1, 45), (18.950000000000003, 'medium', 6, 6, 45), (19.464285714285715, 'short', 1, 1, 45), (19.5, 'shower', 40, 8, 45), (20.107142857142858, 'short', 1, 1, 45), (20.25, 'bath', 140, 14, 45), (20.450000000000003, 'medium', 6, 6, 45), (20.75, 'short', 1, 1, 45), (21.392857142857142, 'short', 1, 1, 45), (21.95, 'medium', 6, 6, 45), (22.035714285714285, 'short', 1, 1, 45), (22.678571428571427, 'short', 1, 1, 45)],
    'Danish house, 4 persons': [(6.6, 'kitchen tap', 1.5, 6, 25), (6.65, 'washbasin', 1, 5, 23), (6.75, 'shower', 52, 7, 38), (6.9, 'kitchen tap', 1.5, 6, 25), (7.0, 'washbasin', 1, 5, 23), (7.1, 'kitchen tap', 1.5, 6, 25), (7.2, 'washbasin', 1, 5, 23), (7.3, 'kitchen tap', 1.5, 6, 25), (7.4, 'washbasin', 1, 5, 23), (7.5, 'kitchen tap', 1.5, 6, 25), (8.0, 'kitchen tap', 1.5, 6, 25), (12.0, 'kitchen tap', 1.5, 6, 25), (12.2, 'kitchen tap', 1.5, 6, 25), (15.5, 'kitchen tap', 1.5, 6, 25), (16.0, 'kitchen tap', 1.5, 6, 25), (16.5, 'kitchen tap', 1.5, 6, 25), (17.0, 'kitchen tap', 1.5, 6, 25), (17.3, 'kitchen tap', 1.5, 6, 25), (17.6, 'kitchen tap', 1.5, 6, 25), (17.9, 'kitchen tap', 1.5, 6, 25), (18.2, 'kitchen tap', 1.5, 6, 25), (18.5, 'kitchen tap', 1.5, 6, 25), (18.8, 'kitchen tap', 1.5, 6, 25), (19.0, 'kitchen tap', 1.5, 6, 25), (19.2, 'kitchen tap', 1.5, 6, 25), (19.5, 'shower', 52, 7, 38), (19.7, 'kitchen tap', 1.5, 6, 25), (20.0, 'kitchen tap', 1.5, 6, 25), (20.3, 'kitchen tap', 1.5, 6, 25), (20.6, 'kitchen tap', 1.5, 6, 25), (21.0, 'kitchen tap', 1.5, 6, 25), (21.5, 'kitchen tap', 1.5, 6, 25), (21.8, 'washbasin', 1, 5, 23), (22.0, 'washbasin', 1, 5, 23), (22.2, 'washbasin', 1, 5, 23), (22.4, 'washbasin', 1, 5, 23)],
    'Danish house, 2 persons': [(7.0, 'shower', 42, 7, 38), (7.1, 'washbasin', 1, 5, 23), (7.2, 'kitchen tap', 1.5, 6, 35), (7.4, 'washbasin', 1, 5, 23), (7.5, 'kitchen tap', 1.5, 6, 35), (12.0, 'kitchen tap', 1.5, 6, 35), (17.5, 'kitchen tap', 1.5, 6, 35), (18.0, 'kitchen tap', 1.5, 6, 35), (18.3, 'kitchen tap', 1.5, 6, 35), (18.6, 'kitchen tap', 1.5, 6, 35), (19.0, 'kitchen tap', 1.5, 6, 35), (19.3, 'kitchen tap', 1.5, 6, 35), (20.0, 'kitchen tap', 1.5, 6, 35), (21.0, 'kitchen tap', 1.5, 6, 35), (22.0, 'washbasin', 1, 5, 23), (22.2, 'washbasin', 1, 5, 23)],
    'Family of 4, morning and evening': [(6.5, 'shower', 42, 7, 40), (6.75, 'shower', 42, 7, 40), (7.0, 'washbasin', 3, 5, 35), (7.1, 'washbasin', 3, 5, 35), (7.25, 'kitchen tap', 2, 6, 45), (7.5, 'washbasin', 3, 5, 35), (12.0, 'kitchen tap', 3, 6, 45), (17.5, 'kitchen tap', 4, 6, 45), (18.0, 'washbasin', 3, 5, 35), (19.0, 'washing up', 10, 6, 45), (20.0, 'shower', 42, 7, 40), (21.5, 'washbasin', 3, 5, 35), (21.6, 'washbasin', 3, 5, 35), (22.0, 'kitchen tap', 2, 6, 45)],
    'Family of 4, all showers in the evening': [(7.0, 'washbasin', 3, 5, 35), (7.1, 'washbasin', 3, 5, 35), (7.25, 'kitchen tap', 2, 6, 45), (7.5, 'washbasin', 3, 5, 35), (12.0, 'kitchen tap', 3, 6, 45), (17.5, 'kitchen tap', 4, 6, 45), (18.0, 'washbasin', 3, 5, 35), (19.0, 'washing up', 10, 6, 45), (19.5, 'shower', 42, 7, 40), (19.75, 'shower', 42, 7, 40), (20.0, 'shower', 42, 7, 40), (21.5, 'washbasin', 3, 5, 35), (21.6, 'washbasin', 3, 5, 35), (22.0, 'kitchen tap', 2, 6, 45)],
    'Couple, morning showers': [(6.5, 'shower', 42, 7, 40), (6.8, 'shower', 42, 7, 40), (7.1, 'washbasin', 3, 5, 35), (7.25, 'kitchen tap', 2, 6, 45), (17.5, 'kitchen tap', 3, 6, 45), (19.0, 'washing up', 8, 6, 45), (22.0, 'washbasin', 3, 5, 35), (22.1, 'washbasin', 3, 5, 35)],
}
PROFILE_INFO = {
    'EN 16147 M': dict(group='Standard test cycles', cite='Reg. (EU) 814/2013 / EN 16147', ref='Commission Regulation (EU) No 814/2013, Annex III, Table 1 (load profiles used for ecodesign and energy labelling; the same profiles are used in EN 16147 for heat pump water heaters).', url='https://eur-lex.europa.eu/eli/reg/2013/814/oj', note='Times, energies and flows as in the regulation. Energies are converted to litres at the use temperature: Tp where the table gives one (bath and floor cleaning 40 °C, dishwashing 55 °C), otherwise Tm (small tappings 25 °C, shower and cleaning 40 °C). Cold water 10 °C. Typical for 1–2 persons.'),
    'EN 16147 L': dict(group='Standard test cycles', cite='Reg. (EU) 814/2013 / EN 16147', ref='Commission Regulation (EU) No 814/2013, Annex III, Table 1 (load profiles used for ecodesign and energy labelling; the same profiles are used in EN 16147 for heat pump water heaters).', url='https://eur-lex.europa.eu/eli/reg/2013/814/oj', note='Times, energies and flows as in the regulation. Energies are converted to litres at the use temperature: Tp where the table gives one (bath and floor cleaning 40 °C, dishwashing 55 °C), otherwise Tm (small tappings 25 °C, shower and cleaning 40 °C). Cold water 10 °C. Typical for a family; two baths.'),
    'EN 16147 XL': dict(group='Standard test cycles', cite='Reg. (EU) 814/2013 / EN 16147', ref='Commission Regulation (EU) No 814/2013, Annex III, Table 1 (load profiles used for ecodesign and energy labelling; the same profiles are used in EN 16147 for heat pump water heaters).', url='https://eur-lex.europa.eu/eli/reg/2013/814/oj', note='Times, energies and flows as in the regulation. Energies are converted to litres at the use temperature: Tp where the table gives one (bath and floor cleaning 40 °C, dishwashing 55 °C), otherwise Tm (small tappings 25 °C, shower and cleaning 40 °C). Cold water 10 °C. Large family; three baths.'),
    'IEA SHC Task 26, weekday': dict(group='Statistical profiles', cite='Jordan & Vajen (2001), IEA SHC Task 26', ref='Jordan, U., Vajen, K. (2001). Realistic domestic hot-water profiles in different time scales. IEA SHC Task 26, Universität Marburg.', url='https://sel.me.wisc.edu/trnsys/trnlib/iea-shc-task26/iea-shc-task26-load-profiles-description-jordan.pdf', note='200 L/day at 45 °C on average. Draw-off categories: short 1 L/min × 1 min (28/day), medium 6 L/min × 1 min (12/day), shower 8 L/min × 5 min (2/day), bath 14 L/min × 10 min (once a week). The original profile has random times; here short and medium draws are spread evenly from 05:00 to 23:00 and the showers are placed in the morning and evening peaks. Weekday without bath.'),
    'IEA SHC Task 26, bath day': dict(group='Statistical profiles', cite='Jordan & Vajen (2001), IEA SHC Task 26', ref='Jordan, U., Vajen, K. (2001). Realistic domestic hot-water profiles in different time scales. IEA SHC Task 26, Universität Marburg.', url='https://sel.me.wisc.edu/trnsys/trnlib/iea-shc-task26/iea-shc-task26-load-profiles-description-jordan.pdf', note='200 L/day at 45 °C on average. Draw-off categories: short 1 L/min × 1 min (28/day), medium 6 L/min × 1 min (12/day), shower 8 L/min × 5 min (2/day), bath 14 L/min × 10 min (once a week). The original profile has random times; here short and medium draws are spread evenly from 05:00 to 23:00 and the showers are placed in the morning and evening peaks. Day with the weekly bath at 20:15.'),
    'Danish house, 4 persons': dict(group='Measured in Danish houses', cite='Marszal-Pomianowska et al. (2021)', ref='Marszal-Pomianowska, A. et al. (2021). Comfort of domestic water in residential buildings: flow, temperature and energy in draw-off points. Field study in two Danish detached houses. Energies 14(11), 3314.', url='https://doi.org/10.3390/en14113314', note='House 1 in the study: 4 occupants, 92 L/day of hot water, 1.6 showers/day of 7–8 min at 35.5–40.4 °C, about 33 short kitchen draws/day (mostly under 20 s, 24.5 °C), hand washing about 23 °C, peaks 06:30–07:00 and 18:00–20:00 on weekdays. Representative weekday built from these statistics; the shower flow of 7 L/min is assumed.'),
    'Danish house, 2 persons': dict(group='Measured in Danish houses', cite='Marszal-Pomianowska et al. (2021)', ref='Marszal-Pomianowska, A. et al. (2021). Comfort of domestic water in residential buildings: flow, temperature and energy in draw-off points. Field study in two Danish detached houses. Energies 14(11), 3314.', url='https://doi.org/10.3390/en14113314', note='House 2 in the study: 2 occupants, about 43 L/day of hot water, 0.8 showers/day, about 11 kitchen draws/day at 35.5 °C. Representative weekday built from these statistics; the shower flow of 7 L/min is assumed.'),
    'Family of 4, morning and evening': dict(group='Illustrative (this book)', cite='illustrative, not from literature', ref='Illustrative profile written for this book, not taken from the literature.', url='', note='Shows the effect of when the showers are taken.'),
    'Family of 4, all showers in the evening': dict(group='Illustrative (this book)', cite='illustrative, not from literature', ref='Illustrative profile written for this book, not taken from the literature.', url='', note='Shows the effect of when the showers are taken.'),
    'Couple, morning showers': dict(group='Illustrative (this book)', cite='illustrative, not from literature', ref='Illustrative profile written for this book, not taken from the literature.', url='', note='Shows the effect of when the showers are taken.'),
}
DEFAULT_PROFILE = 'Family of 4, morning and evening'
# --- end of profiles ---
PROFILE = PROFILES[DEFAULT_PROFILE]

DT = 10.0                        # time step, s
RHO, CP = 994.0, 4182.0          # mean water properties between 10 and 55 C


def tap_demand(t_day, p, profile=PROFILE):
    """Mean flow at the tap (L/s) over the time step starting at t_day (h), and its use temperature.
    Only the part of a tapping that falls inside the step counts, so every tapping has its exact volume.
    Tappings that share a step are added, with a flow-weighted use temperature."""
    step_h = DT / 3600
    f_sum = ft_sum = 0.0
    for start, _, vol, flow, temp in profile:
        vol *= p["use_scale"] / 100
        end = start + vol / flow / 60    # h
        overlap = min(t_day + step_h, end) - max(t_day, start)
        if overlap > 0:
            f = flow / 60 * overlap / step_h
            f_sum += f
            ft_sum += f * temp
    return (f_sum, ft_sum / f_sum) if f_sum > 0 else (0.0, None)


def load_dhwcalc(path, day=None, t_use=45.0):
    """Read a DHWcalc output file and return one day as a tapping profile, plus the file data.

    DHWcalc (Jordan & Vajen, Uni Kassel) writes one value per line: the draw-off flow in L/h for
    each time step, for a whole year (365 or 366 days) or one day. The time step follows from the
    number of lines. DHWcalc volumes carry no temperature; t_use is the draw-off temperature
    (45 C in IEA SHC Task 26). day is 0-based; None picks the day with the median volume."""
    flows = []
    for line in open(path):
        t = line.strip()
        if not t:
            continue
        try:
            flows.append(max(0.0, float(t.replace(";", " ").split()[-1].replace(",", "."))))
        except ValueError:
            pass
    n = len(flows)
    for days in (365, 366, 1):
        if n % days == 0 and abs(1440 / (n / days) - round(1440 / (n / days))) < 1e-9:
            spd, step_min = n // days, round(1440 / (n // days))
            break
    else:
        raise ValueError(f"{n} values: expected one flow value (L/h) per time step for 365 days or one day")
    daily = [sum(flows[d * spd:(d + 1) * spd]) * step_min / 60 for d in range(days)]
    if day is None:
        day = sorted(range(days), key=lambda d: daily[d])[days // 2]
    step_h = step_min / 60
    taps = [(k * step_h, "DHWcalc", f * step_h, f / 60, t_use)
            for k, f in enumerate(flows[day * spd:(day + 1) * spd]) if f > 0]
    return taps, dict(days=days, step_min=step_min, daily_L=daily, day=day)


def cop(t_supply, p):
    tc, te = t_supply + 5 + 273.15, p["T_source"] - 5 + 273.15
    return p["eta_carnot"] * tc / max(tc - te, 1.0)


def simulate(p=DEFAULTS, hours=ALL_HOURS, profile=PROFILE):
    n = int(p["n_layers"])
    m_layer = p["V_tank"] / 1000 * RHO / n                   # kg per layer
    dz = p["H_tank"] / n
    area = p["V_tank"] / 1000 / p["H_tank"]
    g_cond = p["k_eff"] * area / dz                           # W/K between layers
    ua_layer = p["UA"] / n
    # layer index counted from the top: height fraction h -> index
    k_in = min(n - 1, max(0, int(n * (1 - p["inlet_pos"] / 100))))
    k_s = min(n - 1, max(0, int(n * (1 - p["sensor_pos"] / 100))))
    T = [p["T_set"]] * n
    on = False
    steps = int(p["days"] * 24 * 3600 / DT)
    rep0 = int((p["days"] - 1) * 24 * 3600 / DT)
    out = dict(t=[], layers=[], t_tap=[], t_use=[], q_tap=[], q_hp=[], t_ch=[], cop=[])
    s = dict(tapped_kWh=0.0, unmet_kWh=0.0, unmet_min=0.0, hp_kWh=0.0, el_kWh=0.0,
             loss_kWh=0.0, starts=0, run_h=0.0)
    for step in range(steps):
        t = step * DT / 3600
        hour = int(t % 24)
        # control
        if not hours[hour]:
            on = False
        elif not on and T[k_s] < p["T_set"] - p["hyst"]:
            on = True
            if step >= rep0:
                s["starts"] += 1
        elif on and (T[k_s] >= p["T_set"] or T[-1] >= p["T_hp_max"] - p["hex_approach"] - 1):
            on = False   # setpoint reached, or high-temperature cut-out: the return is too warm
        # heat pump and heat exchanger
        m_ch, t_ch, q_hp, c = 0.0, float("nan"), 0.0, float("nan")
        if on:
            m_ch = p["flow_ch"] / 60 / 1000 * RHO                # kg/s
            t_bot = T[-1]
            q_max = m_ch * CP * (p["T_hp_max"] - p["hex_approach"] - t_bot)
            q_hp = max(0.0, min(p["P_hp"] * 1000, q_max))
            t_ch = t_bot + q_hp / (m_ch * CP)
            c = cop(t_ch + p["hex_approach"], p)
        # tapping: thermostatic mixer at the tap
        flow, t_use = tap_demand(t % 24, p, profile)
        m_tap, t_tap, q_tap, q_unmet = 0.0, float("nan"), 0.0, 0.0
        if flow > 0:
            m_mix = flow / 1000 * RHO
            if T[0] > t_use:
                frac = (t_use - p["T_cold"]) / (T[0] - p["T_cold"])
                t_tap = t_use
            else:
                frac, t_tap = 1.0, T[0]
            m_tap = m_mix * frac
            q_tap = m_mix * CP * (t_tap - p["T_cold"])
            q_unmet = m_mix * CP * (t_use - t_tap)
        # energy balance per layer: dT_i = dt/m * sum(inflow * (T_in - T_i)) + conduction + loss
        dT = [0.0] * n
        for i in range(n - 1):                                  # interface between i and i+1
            f_up = m_tap - (m_ch if i >= k_in else 0.0)
            if f_up > 0:
                dT[i] += f_up * CP * (T[i + 1] - T[i])
            elif f_up < 0:
                dT[i + 1] += -f_up * CP * (T[i] - T[i + 1])
            q = g_cond * (T[i + 1] - T[i])
            dT[i] += q
            dT[i + 1] -= q
        dT[-1] += m_tap * CP * (p["T_cold"] - T[-1])
        dT[k_in] += m_ch * CP * ((t_ch if on else T[k_in]) - T[k_in])
        loss = 0.0
        for i in range(n):
            ql = ua_layer * (T[i] - p["T_room"])
            loss += ql
            T[i] += DT * (dT[i] - ql) / (m_layer * CP)
        # buoyancy: mix unstable pairs until the tank is stable
        mixed = True
        while mixed:
            mixed = False
            for i in range(n - 1):
                if T[i + 1] > T[i] + 1e-9:
                    j = i + 1
                    while j + 1 < n and T[j + 1] > T[i]:
                        j += 1
                    avg = sum(T[i:j + 1]) / (j + 1 - i)
                    for k in range(i, j + 1):
                        T[k] = avg
                    mixed = True
        if step == rep0 - 1:
            e_start = sum(T) * m_layer * CP / 3.6e6
        if step >= rep0:
            h = DT / 3600 / 1000
            s["tapped_kWh"] += q_tap * h
            s["unmet_kWh"] += q_unmet * h
            if q_unmet > 1e-6 and t_tap < t_use - 1:
                s["unmet_min"] += DT / 60
            s["hp_kWh"] += q_hp * h
            if on and q_hp > 0:
                s["el_kWh"] += q_hp / c * h
                s["run_h"] += DT / 3600
            s["loss_kWh"] += loss * h
            if (step - rep0) % 6 == 0:                          # store every minute
                out["t"].append(t - (p["days"] - 1) * 24)
                out["layers"].append(list(T))
                out["t_tap"].append(t_tap if flow > 0 else float("nan"))
                out["t_use"].append(t_use if flow > 0 else float("nan"))
                out["q_tap"].append(q_tap / 1000)
                out["q_hp"].append(q_hp / 1000)
                out["t_ch"].append(t_ch)
                out["cop"].append(c)
    s["cop_mean"] = s["hp_kWh"] / s["el_kWh"] if s["el_kWh"] > 0 else float("nan")
    s["T_top_end"], s["T_bot_end"] = T[0], T[-1]
    s["stored_change_kWh"] = sum(T) * m_layer * CP / 3.6e6 - e_start   # closes the balance: hp = tapped + loss + change
    out["summary"] = s
    return out


if __name__ == "__main__":
    for name, prof in PROFILES.items():
        q = sum(v * RHO / 1000 * CP * (tu - DEFAULTS["T_cold"]) for _, _, v, _, tu in prof) / 3.6e6
        print(f"{name:42s} {q:5.2f} kWh/day   {PROFILE_INFO[name]['group']}")
    print()
    r = simulate()
    s = r["summary"]
    print("Last simulated day, default inputs")
    print(f"  heat tapped            {s['tapped_kWh']:6.2f} kWh")
    print(f"  heat not delivered     {s['unmet_kWh']:6.2f} kWh  ({s['unmet_min']:.0f} min more than 1 K too cold)")
    print(f"  heat from heat pump    {s['hp_kWh']:6.2f} kWh")
    print(f"  tank heat loss         {s['loss_kWh']:6.2f} kWh")
    print(f"  change in stored heat  {s['stored_change_kWh']:6.2f} kWh")
    print(f"  electricity            {s['el_kWh']:6.2f} kWh  (mean COP {s['cop_mean']:.2f})")
    print(f"  starts / run time      {s['starts']} / {s['run_h']:.1f} h")
    print(f"  tank top / bottom      {s['T_top_end']:.1f} / {s['T_bot_end']:.1f} C at midnight")
